### ISSUE TITLE
TablePlus 5.1.0 (468) is SUPER buggy

### ISSUE THREAD

**Issue by chrishawn** [TablePlus/TablePlus#2891] opened 2022-11-23 16:54 UTC
I can't even pin down what is going on. I have loved every version of this app until this build.
It crashes.. a lot... working with data in tables will eventually result in empty rows where data should be, blank detail forms, refresh not working until a restart. I am putting this out there in hopes someone working on it goes oh that's when we add the new "X" library.

**Comment by huyphams** [comment] 2022-11-23 16:58
Hi, @chrishawn we don't add any new libs in the recent release. Also, I don't see any significant crashes raise on the crash report.
Did you upgrade macOS? How long since the last time you restart macOS?
Btw, you can always download the old release here: https://tableplus.com/osx/changelog

Please let me know if you're still seeing the issue. I'm closing this issue as it is not so helpful or have any steps to reproduce the issue.

**Closed by huyphams** 2022-11-23 16:58 UTC
