### ISSUE TITLE
Issues on Exported MySQL using TablePlus Windows

### ISSUE THREAD

**Issue by rmondesilva** [TablePlus/TablePlus#1857] opened 2020-05-07 08:48 UTC
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
    - MariaDB 10.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
    - Windows 10: Version 3.4.0 (122) - x64

3. The steps to reproduce this issue: 
    
    1. Select all tables of the database and export as SQL. 
    2. Import this SQL to empty database.

<img width="489" alt="Screen Shot 2020-05-07 at 4 24 19 PM" src="https://user-images.githubusercontent.com/18656034/81273848-132bb080-9082-11ea-9e9a-493bf8027ba3.png">

Importing it on Terminal seems to produce an issue too: 
<img width="738" alt="Screen Shot 2020-05-07 at 4 27 10 PM" src="https://user-images.githubusercontent.com/18656034/81273956-39e9e700-9082-11ea-96a6-c3031f74bb78.png">

But when I use exported SQL from PhpMyAdmin, everything seems to work fine.

**Comment by huyphams** [comment] 2020-05-07 09:04
Thanks @rmondesilva for the feedback. Please try again with the backup feature (on Windows) it will produce the correct dump file.

Regarding the issue, is there any chance of getting the dump example? We want to fix it but not sure how to reproduce the issue.

**Comment by huyphams** [comment] 2020-05-07 10:47
Ah, I think the issue is fixed on this hotpatch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Thanks @rmondesilva

**Closed** 2020-05-08 08:58 UTC
