### ISSUE TITLE
MSSQL: time being returned as 1900-01-01 XX:XX:XX

### ISSUE THREAD

**Issue by funkflute** [TablePlus/TablePlus#952] opened 2019-02-07 15:19 UTC
1. MSSQL
2. Build 190
3. Have a Stored Procedure return a column in format `TIME(0)`, when table plus runs query, it returns 1900-01-01 XX:XX:XX as the time format

start_time, open_time, close_time are all `TIME(0)`

Result of TablePlus
![screen shot 2019-02-07 at 10 12 34 am](https://user-images.githubusercontent.com/7559852/52421269-b974b900-2ac1-11e9-8eb0-df61fc7c301a.png)

Result of SQLPro (and MSSQL's dev tool)
![screen shot 2019-02-07 at 10 12 43 am](https://user-images.githubusercontent.com/7559852/52421275-bb3e7c80-2ac1-11e9-81d0-5c9e3d126d83.png)

**Comment by huyphams** [comment] 2019-02-07 15:21
Thanks @funkflute this bug should be fixed, I'm working on it now.

**Comment by huyphams** [comment] 2019-02-07 15:52
I can't reproduce this issue, I'm using SQL Server 2017 Linux edition. Which is your database version?
Thanks @funkflute

**Comment by funkflute** [comment] 2019-02-07 16:19
Microsoft SQL Server 2014 (SP1-CU9-GDR) (KB3194722) - 12.0.4487.0 (X64) 
	Oct  5 2016 19:04:21 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)

**Comment by huyphams** [comment] 2019-02-08 03:39
Hi @funkflute thanks for the feedback, could you please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 and let me know if it works for you?

**Comment by funkflute** [comment] 2019-02-08 14:02
Still the same result unfortunately:

[image: image.png]

**Comment by huyphams** [comment] 2019-02-11 05:21
Hi @funkflute sorry for the late response, could you show me the data type of the column in the right detail pane?
<img width="596" alt="type" src="https://user-images.githubusercontent.com/3654622/52547119-9581e200-2df7-11e9-91c5-5b2fcff53b12.png">

**Comment by funkflute** [comment] 2019-02-14 13:44
Sorry for the delay, the type is `MSTIME` Thanks!

**Comment by huyphams** [comment] 2019-02-14 13:58
Hi @funkflute I think this build could fix the issue: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if it works for you

**Comment by funkflute** [comment] 2019-02-14 17:55
Success! This fixed the issue.

**Closed** 2019-02-15 18:02 UTC
Labels: bug, done
