### ISSUE TITLE
Enhancement request: Import gzipped SQL files

### ISSUE THREAD

**Issue by mfahy** [TablePlus/TablePlus#889] opened 2019-01-11 22:48 UTC
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL (actually MariaDB 10.x)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

171

3. The steps to reproduce this issue:

When exporting from our company's production databases,  we generally tar/gzip the resulting SQL file to save room on local or temporary storage systems. I hate to even ask this, but any chance you can add the ability to import directly from a gzipped sql file? Sequel Pro provides this (I'm sure you're tired of hearing that), and it's an essential part of our workflow.

This is basically the only feature still keeping me from committing entirely to TablePlus at the moment.

Excellent work, though! Thanks

**Comment by huyphams** [comment] 2019-01-12 02:49
Hey @mfahy I think it's a good and necessary enhancement, I will add it.

**Comment by mfahy** [comment] 2019-01-12 15:14
Awesome, thanks!

**Comment by huyphams** [comment] 2019-01-14 10:49
I've added it on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Could you please give it try? We welcome any feedback!

**Comment by mfahy** [comment] 2019-01-14 16:33
Wow... wasn't expecting an update so quickly. Fantastic work!

It works, but there are some caveats (and one crash):

1. During the import, the progress bar tends to "overshoot" the estimated file size (not a big deal):

![monosnap 2019-01-14 11-11-56](https://user-images.githubusercontent.com/1005838/51126004-01b8f800-17f0-11e9-93f6-9414f3eb1fa7.png)


2. Once the import was finished, the app seemed to end up in weird state. Once I force-quit and restarted, the data I'd imported appeared to be intact, though (quirky):

![laradock pd3_try - mariadb 10 3 10 2019-01-14 11-15-51](https://user-images.githubusercontent.com/1005838/51125700-34aebc00-17ef-11e9-8119-34f2648dd0f4.png)

3. When trying to import a file into an EXISTING database, however, the app simply crashed and had to be restarted (Abridged crash log attached).


[TablePlus2252.log](https://github.com/TablePlus/TablePlus/files/2756063/TablePlus2252.log)



I hope this helps! If you need any other screenshots or information, don't hesitate to ask. Thanks!

**Comment by huyphams** [comment] 2019-01-14 16:46
Thanks for the awesome feedback.
1. I forgot to re-calculate file size after unzipping the file. I will fix it.
2. 3. I will take a look into it.
If everything is tested well, I can release this feature in the next update 180, next month.

**Comment by mfahy** [comment] 2019-01-14 17:02
Thanks! For what it's worth, the files I tested were definitely on the large side (500M+ gzipped). Not sure if this is a contributing factor, but I'd assume it's probably relevant.

**Comment by huyphams** [comment] 2019-01-14 17:34
I fixed the bud 1 and an attempt to fix 2 on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
I'm not sure about the 3 and can't reproduce it, maybe it's related to the 1.

**Comment by mfahy** [comment] 2019-01-15 17:47
Nice, thanks! No. 1 appears to be fixed, but 2 & 3 don't seem any better, I'm afraid. 

Another twist: To determine whether the issue was indeed with the gzip file, I tried to unzip the large gzip file first and then import the SQL directly into an existing database to see if it behaved the same way as the gzipped file. Unfortunately, even the straight SQL file (which admittedly weighs in at 6.86 GB alone) didn't import, either: It didn't crash, but the app simply returned quickly as if I hadn't tried to load anything. Weird.

Sadly, I can't really share the datasets I'm testing with, as they contain protected information, but indeed, they are large.

**Comment by huyphams** [comment] 2019-01-15 18:01
Maybe the file was too big for TablePlus, currently, there are two expensive steps:

1. Unzip the file.
2. Split the plain text into queries.

let me see if I can optimize it, I think step 2 can be optimized.

TablePlus now supports restore a backup file with gz (The backup feature on the welcome screen).

**Comment by mfahy** [comment] 2019-01-15 18:22
Thanks for looking into this -- it's not a huge deal, as I realize my use case is definitely on the fringe, and I can always import large files via Sequel Pro or the mysql cli. Otherwise, TablePlus works for just about everything else I need, and I'm more than happy with it!

Thanks!

**Comment by huyphams** [comment] 2019-01-16 18:08
It was my mistake when adding gzip support, I accidentally broke the read file function (only read two first 2 bit for checking gzip). I have fixed it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Could you try it again?
I have tested with a file 1GB and it works, not sure about the 6.68 GB.

**Comment by mfahy** [comment] 2019-01-16 18:53
Hmmm, I actually have less luck with this latest version:  I cannot import a gzipped file (even a 768K file) at all now -- either to initially populate a new database or to add data to an existing one: The Import Wizard appears blank, and hitting "import" does nothing , but crashes

**Comment by huyphams** [comment] 2019-01-17 01:35
Hmm, weird, thanks @mfahy is there any chance of getting a sample?

**Comment by huyphams** [comment] 2019-01-20 16:34
Hey @mfahy I released the build 183 which fixed an issue when restoring a big dump file. Could you please give it a try. It seems to be fixed on that build.

**Closed** 2019-01-21 07:53 UTC
Labels: done, enhancement, waiting-user-feedback
