### ISSUE TITLE
Double clicking table name to open third tab in trial minimizes window

### ISSUE THREAD

**Issue by codywilliams** [TablePlus/TablePlus#1298] opened 2019-07-10 15:12 UTC
A super small issue but figured I'd create an issue nonetheless.

1. Which driver are you using and version of it: Postgres 9.6.13

2. Which TablePlus build number are you using: 242

3. The steps to reproduce this issue:
In OS X System Preferences ensure double click window title bar is checked and set to "minimize" (under the Dock system preferences). Open TablePlus (free trial). Open two tables so you have two tabs open. Double click a third table in the sidebar. This double-click will open a message saying "Free trial limited 2 tabs" but will also minimize the window, meaning you can't see the message and need to go to the dock to un-minimize before you can get back to the window to click "later", "activate", or "buy now".

**Comment by huyphams** [comment] 2020-09-11 01:49
Duplicate of https://github.com/TablePlus/TablePlus/issues/213

**Closed by huyphams** 2020-09-11 01:49 UTC
Labels: duplicate
