### ISSUE TITLE
Backup Feature can't using in PostgreSQL 10.4 docker version.

### ISSUE THREAD

**Issue by firstziiz** [TablePlus/TablePlus#617] opened 2018-08-28 04:54 UTC
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
> PostgreSQL 10.4 with Docker (postgres:10.4-alpine)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
>Build 122

3. The steps to reproduce this issue:
<img width="699" alt="screen shot 2561-08-28 at 11 47 09" src="https://user-images.githubusercontent.com/4945174/44701356-7943f000-aab8-11e8-9097-11562771ed1c.png">

> I can not use a backup feature in TablePlus, I try to use Docker Postgres:10.4 and then try to use Postgres:10.4-alpine. All of them can not use that feature. I do not know why.
>
> Whoever has experience of using Postgres docker explain to me. please.

**Comment by huyphams** [comment] 2018-08-28 04:57
Hey, looks like the reason because of version mismatch.
We're going to launch a new helper tool DB Engine (which contains more PostgreSQL binaries) as a part of TablePlus set apps and TablePlus will use binaries from that app to perform the backup action. I hope it will resolve all the current backup/restore issue related to versions.

<img width="516" alt="screen shot 2018-08-28 at 11 15 12 am" src="https://user-images.githubusercontent.com/3654622/44701571-90371200-aab9-11e8-8ace-f56cf17972e0.png">

**Comment by firstziiz** [comment] 2018-08-28 07:33
@huyphams Oh : ) Great! I will be waiting to try this feature. Well, How long do you launch this?

**Comment by huyphams** [comment] 2018-08-28 07:37
it will be released next month, TablePlus will support DB Engine after the release, probably at the end of the next month, but the TablePlus Beta can access the feature earlier.

**Comment by firstziiz** [comment] 2018-08-28 07:40
Cool. I already have checked 'Receive Beta Updates'. 🎉

**Comment by johndatserakis** [comment] 2018-09-22 03:33
I'm having a similar issue. When I go to backup a database, the only option in the dropdown is PostgreSQL 10.4 - which is strange because in other parts of table plus is recognizes my correct pg version - which is 10.5. Here is my error:

```
Dumping...
dump_pg_10.4: server version: 10.5 (Debian 10.5-1.pgdg90+1); dump_pg_10.4 version: 10.4
dump_pg_10.4: aborting because of server version mismatch

Dump database done
```
As I mentioned - I'm not sure where it's even getting the 10.4 from. This is running in a local docker machine.

**Comment by firstziiz** [comment] 2018-09-24 15:43
@johndatserakis I have this issue like you. But now fix that by I have written a backup script on Makefile and trigger by a cronjob schedule.

However, I am waiting for working-fine Postgres backup/restore function in TablePlus.

**Comment by bt** [comment] 2018-10-01 17:54
Just came across the same issue myself:

```
Dumping...
dump_pg_10.4: server version: 10.5 (Ubuntu 10.5-0ubuntu0.18.04); dump_pg_10.4 version: 10.4
dump_pg_10.4: aborting because of server version mismatch

Dump database done
```

Hope the team can put in the fix to allow dumping of PostgreSQL 10.5 servers soon (build 136).

**Comment by huyphams** [comment] 2018-10-05 07:05
I just pushed version 139 (open prefences and check on receive updates). Which includes binaries for PostgreSQL 10.5.

**Comment by johndatserakis** [comment] 2018-10-08 16:18
Same here - updated to 139 and get this:

```bash
Dumping...
dump_pg_10.5: server version: 10.5 (Debian 10.5-1.pgdg90+1); dump_pg_10.5 version: 10.5
dump_pg_10.5: aborting because of server version mismatch

Dump database done
```

Thank you for your work on TablePlus

**Comment by lkraider** [comment] 2018-10-11 19:52
Still not working?
```
Create tunneling...
Dumping...
dump_pg_10.5: 
server version: 10.4; dump_pg_10.5 version: 10.5

dump_pg_10.5: aborting because of server version mismatch

Dump database done
```

**Comment by lkraider** [comment] 2018-10-11 21:07
The problem is the shared libraries path:
```
otool -L dump_pg_10.5
dump_pg_10.5:
	/Users/Shared/DBngin/postgresql/10.5/lib/libpq.5.dylib (compatibility version 5.0.0, current version 5.10.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```

There is no `libpq.5.dylib` on that path, it falls back to `/usr/lib/libpq.5.dylib`, which is the old version (default version installed on the mac) and fails.

**Comment by lkraider** [comment] 2018-10-11 21:50
I was able to fix it by changing the dylib search path on the binary, and including the required dylibs in the folder (note that I used the `Postgres.app` binaries below):
```
install_name_tool -change /Applications/Postgres.app/Contents/Versions/10/lib/libpq.5.dylib @loader_path/lib/libpq.5.dylib pg_dump
install_name_tool -change /Applications/Postgres.app/Contents/Versions/10/lib/libpq.5.dylib @loader_path/lib/libpq.5.dylib pg_restore

install_name_tool -change /Applications/Postgres.app/Contents/Versions/10/lib/libcrypto.1.0.0.dylib @loader_path/../lib/libcrypto.1.0.0.dylib lib/libpq.5.10.dylib
install_name_tool -change /Applications/Postgres.app/Contents/Versions/10/lib/libssl.1.0.0.dylib @loader_path/../lib/libssl.1.0.0.dylib lib/libpq.5.10.dylib
install_name_tool -change /Applications/Postgres.app/Contents/Versions/10/lib/libcrypto.1.0.0.dylib @loader_path/../lib/libcrypto.1.0.0.dylib lib/libssl.1.0.0.dylib
```

This is the file structure needed (pg_* binaries can be renamed later):
```
.
├── lib
│   ├── libcrypto.1.0.0.dylib
│   ├── libcrypto.dylib
│   ├── libpq.5.10.dylib
│   ├── libpq.5.dylib
│   ├── libpq.dylib
│   ├── libssl.1.0.0.dylib
│   └── libssl.dylib
├── pg_dump
└── pg_restore
```

**Comment by huyphams** [comment] 2018-10-12 02:31
@bt  if I try to fix the binaries in TablePlus, it is not a full solution. TablePlus will increase the size a lot (up to GB) if it tries to embed all database binaries.

My solution is:
1. TablePlus only embedded the newest (if it's possible) database binaries.
2. If people want to backup/restore database with the old version, the need to install DBngin, which is a database version manager.

**Comment by bt** [comment] 2018-10-12 02:47
I think that's a fair call -- given that PostgreSQL 10.5 is the latest version, I guess the next version of TablePlus will support PostgreSQL 10.5? 😁

**Comment by huyphams** [comment] 2018-10-12 02:59
Yup sure, I will try to fix it first.

**Comment by huyphams** [comment] 2018-10-14 01:39
Hey all, I just updated the binary and change the load path to dynamic as @lkraider suggestion on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Hope it works :D

**Comment by bt** [comment] 2018-10-14 01:41
> Hey all, I just updated the binary and change the load path to dynamic as @lkraider suggestion on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
> Hope it works :D

Success! 🎉 

```
Dumping...
Dump database done
```

**Comment by huyphams** [comment] 2018-10-14 04:33
I released the build 142 which includes 19 bug fixes and new features. (include this one).

**Closed by huyphams** 2018-10-14 04:33 UTC
Labels: enhancement
