### ISSUE TITLE
indentation width in sql query editor is broken

### ISSUE THREAD

**Issue by georgexsh** [TablePlus/TablePlus#1139] opened 2019-04-28 06:42 UTC
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

mysql 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

build 222

3. The steps to reproduce this issue:

indentation width in sql query editor is broken, tab width become one space:

![CleanShot 2019-04-28 at 14 41 08](https://user-images.githubusercontent.com/32751/56859916-b18f2b80-69c3-11e9-86cc-41d310817865.png)

this annoying regression is huge.

**Comment by georgexsh** [comment] 2019-04-28 06:47
another bug related with indention, <kbd>shift+tab</kbd> only works when you have selection, I expect it could unident a line where the cursor is.

**Comment by huyphams** [comment] 2019-04-29 00:05
Hi @georgexsh it's the current indentation is tab, but the default tab size is small.
You can change the indentation to space and it would be better.
<img width="612" alt="indent" src="https://user-images.githubusercontent.com/3654622/56871903-2490b480-6a4d-11e9-83be-ea7f93632538.png">

**Comment by georgexsh** [comment] 2019-04-29 03:38
@huyphams no, I say it's broken cause those settings do not have any effect.

**Comment by georgexsh** [comment] 2019-04-29 04:16
@huyphams because this very regression, I switch back to sequel pro, hope it could be fixed asap.

**Comment by huyphams** [comment] 2019-04-29 04:19
I double check the setting before I commented. So i’m pretty sure that the setting work. You have to press the beautify button after changing the setting.

**Comment by georgexsh** [comment] 2019-04-29 04:26
@huyphams before you close this issue, I guess you could double check with me, IIRC, table plus is a paid software, not a warrant less free thing.

**Comment by georgexsh** [comment] 2019-04-29 04:26
the beautify function is broken too.

**Comment by huyphams** [comment] 2019-04-29 04:43
1. Are you sure that you’ve change the indention to Space? The tab is only 1 character and the width is small, so it looks like a space.
2. Please re-beautify the query after changing the setting.
3. The plugin is not a part of TablePlus so it will not respect the app setting. Maybe we will expose the setting for developer plugin so they can use it. For now, we must modify the plugin if we want custom setting.

**Comment by huyphams** [comment] 2019-04-29 05:12
Please check out this gif 
![2019-04-29 12 08 55](https://user-images.githubusercontent.com/3654622/56877385-d1802700-6a77-11e9-96e1-55585c49ce93.gif)

> @huyphams because this very regression, I switch back to sequel pro, hope it could be fixed asap.

I had closed the issue before because you said that you're using Sequel Pro, and maybe won't have a chance to test the app anymore. I also verified that the setting does work so I'm closed the issue because I think it's a misunderstanding.

**Comment by georgexsh** [comment] 2019-04-29 05:15
i am not “test” table plus, i have already purchased.

**Comment by georgexsh** [comment] 2019-04-29 05:17
what do you mean "The tab is only 1 character and the width is small, so it looks like a space.”?
i have set tab width to “4 spaces”.

**Comment by georgexsh** [comment] 2019-04-29 05:18
yeah if set indentation to Space then use beautify, indentation width is 4.
but that’s not what i want, i expect 1 tab = 4 spaces, as almost every other editor do.

**Comment by huyphams** [comment] 2019-04-29 05:32
it's very complicated to calculate the tab width, it depends on the font, size, and the text system. the best practice is using space as indentation to make sure it 100% works as expected. TablePlus should have used the space as an indentation setting, not tab as the default setting.

**Comment by georgexsh** [comment] 2019-04-29 05:58
@huyphams then i expect press tab key could produce 4 spaces, at the beginning of line.
besides every other editor could do this well.

**Comment by georgexsh** [comment] 2019-04-29 07:02
in short, i want the behavior of previous release back.

**Comment by huyphams** [comment] 2019-04-29 09:55
it's fixed now: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
From the 2.3 we changed the font system (TablePlus allows the user to change to any custom font), so the tab width is not calculated as it does with the fixed font.
Thank you for the feedback.

**Comment by huyphams** [comment] 2019-04-29 10:03
`you should not forbid user to use tab. user will still paste in sql with tab from other sources.
just copy the behavior of any common code editor.`

=> We did not forbid, we will not remove the option to allow user switch back to tab as the indentation.
Tab width may not have the same width in the other edit, because they have a different config, but space will make sure it always looks the same as long as it's the monospaced font.

**Comment by georgexsh** [comment] 2019-04-29 11:45
@huyphams thanks for your prompt response, I tested the build you post, it works.
but as a subscriber of setapp, I guess I need wait for the next release.

**Comment by georgexsh** [comment] 2019-04-29 11:46
> The tab may not have the same width in the other edits, because they have a different config

**Comment by georgexsh** [comment] 2019-04-29 11:57
> The tab may not have the same width in the other edits, because they have a different config

I call this a _bug_.

> so the tab width is not calculated as it does with the fixed font.

i think it is okay, tab width just affect the beginning of a line, not in the middle,  as long as the width is consistent, and as long as  it is only one space wide...

**Closed** 2019-05-01 01:32 UTC
Labels: bug, done

**Comment by BrandonBlair** [comment] 2019-05-02 15:35
> @huyphams nope, I say it's broken cause those settings do not have any effect, even switch to “ident with spaces”.

Having the same issue. Choosing spaces or tabs has no effect. Press tab, it advances one space. Fairly crucial functionality for an editor.

**Comment by huyphams** [comment] 2019-05-02 15:37
Hi @BrandonBlair it has been fixed on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by BrandonBlair** [comment] 2019-05-02 15:48
Thanks for getting this fixed. Tabs work in this build, but on deleting it still treats them as spaces. A minor annoyance, but one that should be addressed eventually. Deleting a tab should be a single delete, not 4.

**Comment by huyphams** [comment] 2019-05-02 15:50
You must change the setting back to tabs @BrandonBlair and it should be a single character.
<img width="482" alt="tab" src="https://user-images.githubusercontent.com/3654622/57088501-a2dea680-6d2c-11e9-9bca-dc3f84477a69.png">

**Comment by BrandonBlair** [comment] 2019-05-02 16:10
![tabs](https://user-images.githubusercontent.com/5199091/57089734-b822e900-6cca-11e9-9479-2786cf5f5414.gif)
That has no effect. This is on the latest build you linked from Dropbox (224)

**Comment by huyphams** [comment] 2019-05-02 16:15
ahh, yeah, this is the other issue (the original issue is related to Beautify function).
I just double check and you've to close and reopen the editor to take effect. I will take a look into it and improve with hot reload config.

**Comment by BrandonBlair** [comment] 2019-05-02 16:19
Awesome - I appreciate you taking this feedback, I know you're probably already busy. This will make it a better product for sure.

**Comment by BrandonBlair** [comment] 2019-05-02 16:21
Confirmed it takes the setting once I reload.

**Comment by aurora** [comment] 2020-01-14 20:24
think there's still an issue with indentation when using SPACES - for me TablePlus inserts 4 spaces regardless if there are 4 spaces to the next tabstop required or not.
