### ISSUE TITLE
Switching from other windows takes 5-10 seconds

### ISSUE THREAD

**Issue by kubaczer** [TablePlus/TablePlus#3183] opened 2023-12-21 12:35 UTC
I have top of the line MacBook Pro and switching from other applications to TablePlus takes ages (5-10 seconds, to be more exact), has been like that for years.
I keep many remote connections open at the same time in a single window. After I restart app it works relatively fine for some time, but quickly it's back to almost unusable.
I love the app so much, I keep using it nevertheless and keep paying for subscription renewals, but sadly will have to look for different solutions if this issue doesn't get resolved quickly.

Most of my connections are MySQL 5.7.42.
My current version is 5.6.6 (520), but, as mentioned before, have run into this issue for years now.

**Comment by huyphams** [comment] 2023-12-21 17:23
Hi @kubaczer I'm sorry for the issue but could you please give me more the info how to reproduce the issue?
What was talking 5-10 seconds? establishing the connection or app lag or something?

**Comment by kubaczer** [comment] 2023-12-21 17:32
Hi, so when I do "cmd + tab" into TablePlus, it takes that long before app actually becomes visible.
Should have mentioned another thing: once app is visible and allowing interaction it take few seconds whenever I want to switch to another db by clicking on one of the db icons on side bar on the left. What happens in that scenario: I click on the db icon, but then have to have for a few seconds before anything changes on the screen.

**Comment by huyphams** [comment] 2023-12-21 17:34
I wonder if you have set the paging number to a very large value? How many rows per page are you using? the default is 300.

**Comment by kubaczer** [comment] 2023-12-21 17:36
It looks like my current limit is 100. I believe I adjusted down from 300 recently. Don't think it helped the performance, though.

**Comment by kubaczer** [comment] 2023-12-21 17:57
#1888 - looks like I'm not the only one affected

**Comment by huyphams** [comment] 2023-12-21 18:00
are you opening any long text in SQL Query?

**Comment by kubaczer** [comment] 2023-12-21 18:04
Not sure what you mean, but I have multiple "SQL Query" tabs, none of them being longer than 100-200 lines of sql.

Possibly not related to your question, but slowdown doesn't seem to be related to which db connection is currently selected etc. (some db connections come with more "SQL Query" or table tabs)

**Comment by huyphams** [comment] 2023-12-21 18:08
Apple dropped support for TextView a long time ago, and its performance is really, really bad. I think it will still be slowed down if you open it (regardless of whether it's visible or not).

Can you confirm this by closing all those SQL Query tabs and see how it goes?


We're building a new replacement native text view but it will not be available anytime soon, maybe mid next year. I don't want to use the web technology, such as Monaco editor from VSCode because TablePlus is a native code. But I think I could give the user change to monaco an option is a temporary solution.

**Comment by kubaczer** [comment] 2023-12-21 18:15
Have just reopened app, so delay isn't awful at the moment anyway (1-2 second), which makes it hard to test your hypothesis. Have closed all "SQL Query" tabs, delay is still at 1-2 second. I don't know, maybe it's a baseline delay, wouldn't be great, but manageable.

Will wait a day or two two see if performance regresses as it has always done. If it does, will again make sure all query tabs are closed. Then will be able to tell if this helps and will let you know. Thanks for your time

**Comment by kubaczer** [comment] 2023-12-21 18:18
Also. If it's related to TextView - would it be a CPU bottleneck and would I see a CPU usage spike?
(haven't checked whether cpu spike is there, but will do)

**Comment by huyphams** [comment] 2023-12-21 18:18
Yep, thank you so much!

**Comment by huyphams** [comment] 2024-01-04 17:34
Hi @kubaczer it could be an issue where you opened so many databases on the left sidebar, how many databases are you opening?

**Comment by kubaczer** [comment] 2024-01-04 17:36
Hey. I have 20 tabs on the left side, many are often inactive, but w/o frequent app restarts I likely reach 10-15 active at a time

**Comment by huyphams** [comment] 2024-01-04 20:36
Hi @kubaczer I resolved the issue in this patch, I think it is much better now, you can download here:
https://www.dropbox.com/scl/fi/hnm7thxakh676o9zzlr0j/TablePlus.dmg?rlkey=d7owts2c3xe4e0pme95q2rona&dl=0
Thanks

**Comment by kubaczer** [comment] 2024-01-04 21:38
Need to test for a few more days, but right now feels like night and day, way quicker to load. This will **really** help w/ my workflow. Thanks!

**Comment by huyphams** [comment] 2024-01-04 22:58
I have found some issues when you reorder the items on the left sidebar, but I fixed it, you can redownload the patch if you want (the same link above).

**Closed** 2024-01-04 23:58 UTC
