### ISSUE TITLE
Feature Request: Cluster Support for Redis

### ISSUE THREAD

**Issue by cnzmc** [TablePlus/TablePlus#2230] opened 2020-12-10 01:31 UTC
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Redis 6.0.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.12.0(354)

3. The steps to reproduce this issue:
Better if TablePlus can support redis cluster.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment] 2020-12-10 11:57
Hi @cnzmc thank you, it's a duplicate of https://github.com/TablePlus/TablePlus/issues/1280

**Closed by huyphams** 2020-12-10 11:57 UTC
