### ISSUE TITLE
How to do paralel query on same database

### ISSUE THREAD

**Issue by aaginsa** [TablePlus/TablePlus#1756] opened 2020-03-03 03:53 UTC
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.x
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
296
3. The steps to reproduce this issue:
Command + Shift + K on same connection, choose same database fail

I need to work with multiple paralel query on same database. I found 2 problems
- On tableplus, even i have multiple "SQL Query" Tab, i can't have paralel query
- So what i'm trying to do is open new connection, choose same connection (same IP), choose same database, but it keep jumping to previous connection (previous connection tab)

So i need help, how can i do multiple paralel query on same connection & database ?

<img width="1440" alt="Screen Shot 2020-03-03 at 10 46 43" src="https://user-images.githubusercontent.com/58243816/75741289-bf78b000-5d3c-11ea-8ba7-9c2799a3b552.png">

**Comment by aaginsa** [comment] 2020-03-04 02:16
Hi @huyphams can you point out the same issue that i can follow? thanks

**Comment by huyphams** [comment] 2020-09-14 02:34
It's a duplicate of https://github.com/TablePlus/TablePlus/issues/456

**Closed by huyphams** 2020-09-14 02:34 UTC
Labels: duplicate
