### ISSUE TITLE
Create Table SQL DDL does not auto refresh table in list

### ISSUE THREAD

**Issue by wayneforrest** [TablePlus/TablePlus#2106] opened 2020-09-24 22:02 UTC
1. MariaDB 10.5.5

2. 3.9.1 (342)

3. STEPS

3.1: Open SQL editor, and create a table.
3.2 Execute the DDL statement.
3.3 Notice that the Table is not in the TABLE LIST.
3.4 Hit "refresh" and the table appears.

**Comment by huyphams** [comment] 2020-09-24 22:55
Hi @wayneforrest it's a duplicate of https://github.com/TablePlus/TablePlus/issues/1874

**Closed by huyphams** 2020-09-24 22:55 UTC
