### ISSUE TITLE
Beautify Tweaks

### ISSUE THREAD

**Issue by Akkadius** [TablePlus/TablePlus#922] opened 2019-01-25 02:05 UTC
First off, let me just say, been working with databases for 10-15 years, this browser is fucking awesome. I've used Navicat Premium, Sequel Pro mostly over that time frame. I've recently purchased and switched this over to my daily driver

**Issue:** When beautifying queries (Which is so damn nice) there are a few small quirks

1) When I complete a statement with a semicolon and I hit enter onto the next line, I would expect it to return to the first caret position in the new line

![2019-01-24 19 59 43](https://user-images.githubusercontent.com/3319450/51720433-2a709700-2013-11e9-8803-35b3248a1808.gif)

2) Very similarly to above, if I type another query I might just ignore the fact that it doesn't return to the begging of the line and try to let the beautifier (Hotkey) bring the beginning of the statement to the beginning of the line and it does not

![2019-01-24 20 02 25](https://user-images.githubusercontent.com/3319450/51720437-33f9ff00-2013-11e9-926c-7b3e297bf1ad.gif)

---

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

1.2 (182)

3. The steps to reproduce this issue:

See GIFS

---

Let me know if you want me to provide anything else

**Comment by huyphams** [comment] 2019-01-25 02:10
Hey @Akkadius thanks for the kind words.
We're working on some big update for the TablePlus Text Editor, that update is really awesome, it resolves some current limitations of TablePlus.
1. Open big file SQL.
2. Multiple carets while editing.
I noted your feedback on the backlog and will improve it on that update.

FYI: a demo of that update: https://twitter.com/TablePlus/status/1049309391231438849

**Comment by Akkadius** [comment] 2019-01-25 02:12
That's awesome! I'm rooting for you guys 🥂🍻💪

**Comment by Akkadius** [comment] 2019-02-13 23:17
So this update fixed the aforementioned issues above, but I would check beautifying during the use of subselects, it used to get nested somewhat nicely but now it is completely collapsed and harder to read

**Comment by huyphams** [comment] 2019-02-14 01:04
Hi @Akkadius that's my mistake, on the new build 190, TablePlus respects the tabs/spaces config but I forgot the indent level for tabs. This build should fix that issue: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by Akkadius** [comment] 2019-02-14 01:10
No worries! I really love this editor! Keep up the great work!

**Comment by huyphams** [comment] 2019-02-15 18:08
I released it on the new build 194, so I will close this issue. Thanks!

**Closed by huyphams** 2019-02-15 18:08 UTC

**Comment by Akkadius** [comment] 2019-02-17 01:49
Multiple sub-selects does not organize very well still on build 194, it keeps nesting each statement instead of doing something like this

Current
![image](https://user-images.githubusercontent.com/3319450/52907269-c4e38500-3223-11e9-9f8c-de6b97593794.png)

Something more readable
![image](https://user-images.githubusercontent.com/3319450/52907275-f1979c80-3223-11e9-9ce5-26ab138a5c0d.png)

**Comment by huyphams** [comment] 2019-02-17 01:51
Thanks @Akkadius can I have an actual string instead of the image? I want to check it.

**Comment by Akkadius** [comment] 2019-02-17 01:52
```SELECT
	account_settings.account_id, (
		SELECT
			`name`
		FROM
			account
		WHERE
			account_id = account_settings.account_id) AS account_name, (
			SELECT
				count(id) AS resize_count
			FROM
				product_file
			WHERE
				account_id = account_settings.account_id
				AND resize_count > 1
				AND date_added > '2019-02-06 17:28:15') AS successful_resizes_new_resize, (
				SELECT
					count(id) AS resize_count
				FROM
					product_file
				WHERE
					account_id = account_settings.account_id
					AND resize_count = -4
					AND date_added > '2019-02-06 17:28:15') AS errored_resizes_new_resize, (
					SELECT
						count(id) AS resize_count
					FROM
						product_file
					WHERE
						account_id = account_settings.account_id
						AND cdn_resized IS NOT NULL
						AND resize_count > 1) AS total_product_resizes
				FROM
					account_settings
				WHERE
					setting_handle LIKE '%image_resize_processor%'
				ORDER BY
					successful_resizes_new_resize DESC;
```

**Comment by Akkadius** [comment] 2019-02-17 01:52
There ya go ^ 😁

**Comment by huyphams** [comment] 2019-02-17 02:04
@Akkadius Please press: Command + L > SQL Formatter Plugin > Install

After installing that plugin.

Open Query Editor: Select the query > Control + I or Main Menu > Plugin > Format SQL it should work as your expected.

**Comment by Akkadius** [comment] 2019-02-17 02:08
Even with that enabled it still doesn't format any differently 

![image](https://user-images.githubusercontent.com/3319450/52907402-961ade00-3226-11e9-94c1-2f019d91effc.png)

Result

![image](https://user-images.githubusercontent.com/3319450/52907405-9f0baf80-3226-11e9-95be-01cf87c5fbdc.png)

Even tried restarting TablePlus

And yeah I use Control + I all the time, one of my favorite parts of the editor! 😄

**Comment by huyphams** [comment] 2019-02-17 02:10
Are you sure that you press control + I and not command + I? Btw, have you tried Main Menu > Plugin > Format SQL?

**Comment by Akkadius** [comment] 2019-02-17 02:12
Ahhh I thought you mean Command + I because Control is your windows equivalent so that is kind of confusing.

Yes with Control (Mac) it formats correctly

![image](https://user-images.githubusercontent.com/3319450/52907434-2527f600-3227-11e9-8892-2b6422f1a9f1.png)

**Comment by huyphams** [comment] 2019-02-17 02:30
You can custom the shortcut key yourself by fork and edit this source: https://github.com/TablePlus/sql-formatter but the problem is there are some system menu item is using Command + I at the time and it overrides the shortcut if you change it to command + i.
I will investigate it and let see if I can force the shortcut key if the user installs it via the plugin system.

**Comment by Akkadius** [comment] 2019-02-17 02:31
That's fine, why do we have to use a plugin to get desired beautify formatting over using the plugin?

**Comment by huyphams** [comment] 2019-02-17 02:36
I wrote it because the original formatter is used for all drivers. It's really hard to custom and everybody has their own favorite format. Btw, Plugin is more than that, you can do whatever you want with the text, not only formatting it.

**Comment by Akkadius** [comment] 2019-02-17 02:39
That makes total sense from a developer standpoint, from a user standpoint folks are going to be confused just like I was why it wasn't formatting correctly. Maybe hook a one time notification popup informing users that there are plugins that do this better? Or maybe make the SQL formatter plugin over-ride for MySQL connections? I never knew this thing had plugins until you told me

Regardless of all of these issue, I absolutely love this editor and keep it up. I've shot you guys money already I'm sure I'll do more over time

**Comment by huyphams** [comment] 2019-02-17 02:41
Yeah, that's exactly I want to do, TablePlus should suggest plugin (just like VSCode does) but I have a soo many tasks, but sure that's the plan. Thanks for the license!

**Comment by Akkadius** [comment] 2019-02-17 02:42
Task list is never ending for a developer and always a struggle to prioritize, but one thing that helps you keep moving is knowing that people love what you're doing!

Cheers!

-Chris

**Comment by gene-blink** [comment] 2020-01-07 06:05
can you give an example of how to modify plugin to customize the way it formats? I looked all through the plugin code and do not see any obvious ways to do that. 
for example, i prefer commas preceding a column on the line below. 

so not this ...

SELECT
	foo,
	bar,
	baz
FROM
	q
WHERE
	d = 1;

but this ...

SELECT foo
              ,bar
              ,baz
   FROM q
WHERE d = 1;
