### ISSUE TITLE
macOS - The query "log view" width is too small - no options to change it

### ISSUE THREAD

**Issue by Artum** [TablePlus/TablePlus#2203] opened 2020-11-26 06:36 UTC
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0.21

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.10.0 (348)

3. The steps to reproduce this issue:
Nothing really special:

- Open TablePlus
- Select DB
- Click on "SQL" icon to open query editor
- Run simple query
- Observe that below the query editor there is a result screen with the table that the query fetched and additional screen which is the log. See [this screenshot](https://postimg.cc/R63SnMFQ).

**Comment by huyphams** [comment] 2020-11-26 06:39
It's duplicate of https://github.com/TablePlus/TablePlus/issues/1973
It as an AppKit bug and I still finding a way to fix this issue.

**Closed by huyphams** 2020-11-26 06:39 UTC
