### ISSUE TITLE
Error connecting to lightsail at AWS "Can't connect to MySQL server on 'ENDPOINT.rds.amazonaws.com' (10060)"

### ISSUE THREAD

**Issue by mdimichele** [TablePlus/TablePlus#2364] opened 2021-03-24 10:29 UTC
1. The driver is MySql

2. I'm using TablePlus build 150

3. Host is the AWS endpoint
4. Port is 3306 per AWS database screen

5. Cannot connect to AWS Lightsail database with the following error:

Can't connect to MySQL server on 'ENDPOINT_HERE.rds.amazonaws.com' (10060)

The endpoint, user, and password were copy and pasted from the AWS screen.

Any help would be great.  Thanks in advance.

**Comment by huyphams** [comment] 2021-03-24 11:07
Hi, @mdimichele please check the firewall (Amazon has a default firewall and allowed IP list) and make sure that the credentials are correct. You can also use MySQL Workbench to confirm the credentials. I believe the issue is not related to TablePlus.
I'm closing the issue now because this is the macOS repo, the Windows repo here: https://github.com/TablePlus/TablePlus-Windows/issues
Thanks.

**Closed by huyphams** 2021-03-24 11:07 UTC
