### ISSUE TITLE
[BUG] - Buy license is cutoff as Buy licen

### ISSUE THREAD

**Issue by PeterNgTr** [TablePlus/TablePlus#2281] opened 2021-01-15 11:53 UTC
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 3.12.2 (358)

3. The steps to reproduce this issue:

- Open Tableplus
- Click Tableplus > Register License...
- Observe the popup

Buy license text is cutoff
<img width="568" alt="Screen Shot 2021-01-15 at 12 51 22 PM" src="https://user-images.githubusercontent.com/7845001/104724196-a13b5900-5730-11eb-8e81-554b09637af0.png">

**Comment by huyphams** [comment] 2021-01-15 12:01
It's a duplicate of https://github.com/TablePlus/TablePlus/issues/2280 and we've fixed it. Thank you!

**Closed by huyphams** 2021-01-15 12:01 UTC
