### ISSUE TITLE
table list does not contains newly created table (and no way to refresh the list)

### ISSUE THREAD

**Issue by enyosolutions** [TablePlus/TablePlus#1874] opened 2020-05-13 15:17 UTC
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 286

3. The steps to reproduce this issue:
- Create a new table using sql. 
- look into or filter the list of tables on the side.

There is no way to refresh the tables list...

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment] 2020-05-13 15:29
hi @enyosolutions You can press command + R to refresh or click the refresh button on the toolbar
Also, your build is very old, please update to our latest release 308.

**Comment by huyphams** [comment] 2020-05-13 15:55
Duplicate of https://github.com/TablePlus/TablePlus/issues/1748

**Closed by huyphams** 2020-05-13 15:55 UTC
