### ISSUE TITLE
why setapp tableplus still  Intel  not M1

### ISSUE THREAD

**Issue by PromiseNev** [TablePlus/TablePlus#2553] opened 2021-11-19 15:46 UTC
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.
![image](https://user-images.githubusercontent.com/16667188/142650928-0b9865a3-627c-4e47-86d7-f63bc947e619.png)

**Comment by jakobhviid** [comment] 2021-12-01 14:19
I have the same problem. Attaching photo showing that it is the intel version:
<img width="1076" alt="Screenshot 2021-12-01 at 15 18 42" src="https://user-images.githubusercontent.com/4179396/144250730-487d97f7-1469-419b-b881-87b3254a4e91.png">

**Comment by huyphams** [comment] 2021-12-01 14:25
Duplicate of https://github.com/TablePlus/TablePlus/issues/2180

**Closed by huyphams** 2021-12-01 14:25 UTC
