### ISSUE TITLE
Feature request: search capability for results, not only for tables

### ISSUE THREAD

**Issue by BFJonk** [TablePlus/TablePlus#1524] opened 2019-10-30 17:36 UTC
Hi, you have an excellent search function when you display a table. 

It would be nice to be able to serach, filter, sort on results as well

**Comment by huyphams** [comment] 2020-05-24 07:01
It's implemented and will be released in the next update. I'm closing this issue because it's a duplicate of https://github.com/TablePlus/TablePlus/issues/530

**Closed by huyphams** 2020-05-24 07:01 UTC
Labels: duplicate, enhancement

**Comment by cotfas** [comment] 2020-05-24 07:07
+1
