### ISSUE TITLE
Search in the Tables navigation returns incorrect results

### ISSUE THREAD

**Issue by danagnostos** [TablePlus/TablePlus#2528] opened 2021-10-21 07:31 UTC
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
TablePlus Version 4.2.0 (388)

3. The steps to reproduce this issue:
1. Connect to a database that has many tables (50-60 or more)
2. Expand the Tables navigation
3. Search for something. You will most likely notice that many irrelevant tables will be shown. For instance I performed a search for the string 'raci' and expected to see just one table as there were no other tables with 'raci' in their name (see the attached screenshot).

Noted: If the bug is related to data, please attach an example SQL data.
<img width="456" alt="Screenshot 2021-10-21 at 10 30 37" src="https://user-images.githubusercontent.com/14981130/138231673-d1b81c32-7ec0-41ea-91fb-29181a9550eb.png">

**Comment by huyphams** [comment] 2021-10-21 07:32
Duplicate of https://github.com/TablePlus/TablePlus/issues/2351
TablePlus uses fuzzy matching by default. You can add a double quote to force TablePlus search "contains".

**Closed as completed by huyphams** 2021-10-21 07:32 UTC
