### ISSUE TITLE
"Discard all changes?" Warning

### ISSUE THREAD

**Issue by tomrossi7** [TablePlus/TablePlus#2094] opened 2020-09-17 15:53 UTC
There are two possibly related issues on **Build 343**, with the option disabled to **Automatically save queries while editing option**

1. You will always be prompted with a warning to "Discard all changes?" even if you haven't made any changes.
2. If you have more than 2 queries open, and attempt to quit the application, the choosing "Discard" will not allow you to quit the application. Instead, it just keeps prompting with the warning.

**Comment by j-ro** [comment] 2020-10-21 17:46
plus one, have this bug, have to force quit

**Comment by deepcoder** [comment] 2020-10-28 02:41
plus one as well. Even if you run a query that only returns completion flag of successful execution, you receive the warning dialog. Example in Postgresql:
Query:
SET TIMEZONE = 'America/Los_Angeles';
Result:
Query 1 OK: SET

You should be able to close this tab without a prompt to discard.

**Comment by tomrossi7** [comment] 2021-01-22 15:54
Any chance this could be addressed soon 😬 ?

**Comment by tomrossi7** [comment] 2021-08-23 14:05
This issue is so annoying. Can someone please let us know if this will be fixed?

**Comment by huyphams** [comment] 2021-08-23 14:41
Hi, please find the hotpatch in the link below: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Please let me know if you are still seeing the issue.

**Closed by huyphams** 2021-08-23 14:41 UTC

**Comment by tomrossi7** [comment] 2021-08-23 14:46
Thanks @huyphams this is a great improvement! This fixed the second issue I listed, but not the first:

> You will always be prompted with a warning to "Discard all changes?" even if you haven't made any changes.

**Comment by huyphams** [comment] 2021-08-23 14:47
Do you have the step to reproduce the 1st issue? I could not reproduce it.

**Comment by tomrossi7** [comment] 2021-08-23 14:54
Actually, even when I reloaded it, I still have both issues with the second issue.

1. Open TablePlus
2. Run Saved query (simple select query)
3. <cmd>-<q>
4. Unable to dismiss modal

Do you have an email I can send screen recording?

**Comment by huyphams** [comment] 2021-08-23 15:41
Thanks, please try this hotpatch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
it should fix both of your issue and also the @deepcoder issue
Thanks all

**Comment by tomrossi7** [comment] 2021-08-23 16:14
@huyphams yes! I can confirm everything appears to be working great! Do I just need to tell it to not automatically update to newer versions (it prompts me)?

**Comment by huyphams** [comment] 2021-08-23 16:17
You can use this build as official release, it will work just like the one you downloaded on our website. No worries.
