### ISSUE TITLE
Can not connect to MySQL over SSH

### ISSUE THREAD

**Issue by keremkayhan** [TablePlus/TablePlus#439] opened 2018-05-28 19:40 UTC
MySQL version 5.7.22
Build 107

1- Fill connection form with SSH user credentials
2- Test connection --> OK (all inputs green)
3- Connect

Result: Stuck on connection screen.

**Comment by huyphams** [comment] 2018-05-29 02:28
Hi @keremkayhan may I ask you some question about your setup?

1. How big is your database (thousands table, thousands database)...
2. Have you entered `database name` in connection form?

I think there is an issue when loading some metadata, can you leave the database name field empty and try again?

<img width="612" alt="aaa" src="https://user-images.githubusercontent.com/3654622/40635089-907af828-6322-11e8-9e6c-74c84bb974dd.png">

**Comment by keremkayhan** [comment] 2018-05-29 07:00
Hey @huyphams,

1. It is not a big databese. (9 databases at the moment)
2. Database name was already empty. (I tried it with a database name. No change)

![image](https://user-images.githubusercontent.com/5699037/40642737-ac7aa704-6326-11e8-9e7d-c8ab5e48e9e2.png)

**Comment by huyphams** [comment] 2018-05-30 07:32
Hi @keremkayhan looks like the server you ssh is not the database server, is that the proxy server?
And can you show me the message was shown on the workspace screen?
<img width="1222" alt="aa" src="https://user-images.githubusercontent.com/3654622/40705828-230d4dd2-6416-11e8-9745-d368f7690ed3.png">

**Comment by keremkayhan** [comment] 2018-05-31 16:21
Hey @huyphams, I can connect to the server over SSH with Sequel Pro or any other database clients.
And here is the message. 
Thanks.

![image](https://user-images.githubusercontent.com/5699037/40794365-98a197f0-6507-11e8-82d9-6f122636757d.png)

**Comment by wzrd** [comment] 2018-07-10 18:46
@keremkayhan , had exactly the same problem. Solved it by typing 127.0.0.1 in Host field of database. I used the same as my server's ip, that was wrong, but it worked with Sequel Pro. Hope it helps.

**Comment by bounoable** [comment] 2018-08-01 18:43
@wzrd thank you! that was the solution for me, too.

**Comment by marcusnunes** [comment] 2018-10-06 15:09
I was with the same problem. 
Changing host to 127.0.0.1 solve the problem.
Thank you

**Comment by dennisirmscher** [comment] 2018-11-27 14:56
I'm afraid I have the same problem. My database server is not the same as the web server, but it is only accessible from the web server through the firewall, so changing the host to 127.0.0.1 is not an option for me.
All access credentials are correct, I can use the Bash to log in with them without any problems. If I want to test the connection in TablePlus, the fields for SSH server, port and user immediately turn green. However, the fields for the database remain unchanged, the button "Test" remains grayed out. When trying to connect, TablePlus hangs at "Connecting to database..." as described above. The following logs will be created, no idea if they are helpful in any way:

```
standard	15:52:27.891397 +0100	TablePlus	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 611 vs 892, 512, <private>
standard	15:52:27.923007 +0100	TablePlus	Task <69BB5F40-14FC-464F-BF7A-2F5BFC0B201C>.<101> resuming, QOS(0x9)
standard	15:52:27.923418 +0100	TablePlus	Task <69BB5F40-14FC-464F-BF7A-2F5BFC0B201C>.<101> {strength 1, tls 8, ct 0, sub 0, sig 0, ciphers 1, bundle 0, builtin 0}
standard	15:52:27.923644 +0100	TablePlus	TIC Enabling TLS [24:0x600002372880]
standard	15:52:27.923692 +0100	TablePlus	TIC TCP Conn Start [24:0x600002372880]
standard	15:52:27.923820 +0100	TablePlus	[C24 Hostname#c61e2d6a:443 tcp, url: https://e.crashlytics.com/spi/v2/events, tls, no cellular] start
standard	15:52:27.924166 +0100	TablePlus	nw_connection_report_state_with_handler_locked [C24] reporting state preparing
standard	15:52:27.925284 +0100	TablePlus	Task <69BB5F40-14FC-464F-BF7A-2F5BFC0B201C>.<101> setting up Connection 24
standard	15:52:28.047493 +0100	TablePlus	nw_socket_handle_socket_event [C24.1:3] Socket received CONNECTED event
standard	15:52:28.047598 +0100	TablePlus	nw_endpoint_flow_protocol_connected [C24.1 IPv4#bf54582d:443 in_progress socket-flow (satisfied)] Transport protocol connected
standard	15:52:28.050943 +0100	TablePlus	TIC TLS Event [24:0x600002372880]: 1, Pending(0)
standard	15:52:28.051115 +0100	TablePlus	TIC TLS Event [24:0x600002372880]: 2, Pending(0)
standard	15:52:28.151115 +0100	TablePlus	TIC TLS Event [24:0x600002372880]: 2, Pending(0)
standard	15:52:28.154156 +0100	TablePlus	TIC TLS Event [24:0x600002372880]: 11, Pending(0)
standard	15:52:28.154246 +0100	TablePlus	TIC TLS Event [24:0x600002372880]: 14, Pending(0)
standard	15:52:28.180411 +0100	TablePlus	System Trust Evaluation yielded status(0)
standard	15:52:28.181749 +0100	TablePlus	TIC TLS Trust Result [24:0x600002372880]: 0
standard	15:52:28.282229 +0100	TablePlus	nw_endpoint_flow_protocol_connected [C24.1 IPv4#bf54582d:443 in_progress socket-flow (satisfied)] Output protocol connected
standard	15:52:28.282462 +0100	TablePlus	nw_connection_report_state_with_handler_locked [C24] reporting state ready
standard	15:52:28.283183 +0100	TablePlus	TIC TLS Event [24:0x600002372880]: 20, Pending(0)
standard	15:52:28.283370 +0100	TablePlus	TIC TCP Conn Connected [24:0x600002372880]: Err(16)
standard	15:52:28.283794 +0100	TablePlus	TIC TCP Conn Event [24:0x600002372880]: 1
standard	15:52:28.283824 +0100	TablePlus	TIC TCP Conn Event [24:0x600002372880]: 8
standard	15:52:28.283872 +0100	TablePlus	TIC TLS Handshake Complete [24:0x600002372880]
standard	15:52:28.284718 +0100	TablePlus	Task <69BB5F40-14FC-464F-BF7A-2F5BFC0B201C>.<101> now using Connection 24
standard	15:52:28.284990 +0100	TablePlus	nw_endpoint_flow_protocol_connected [C24.1 IPv4#bf54582d:443 ready socket-flow (satisfied)] Output protocol connected
standard	15:52:28.285933 +0100	TablePlus	Task <69BB5F40-14FC-464F-BF7A-2F5BFC0B201C>.<101> sent request, body S
standard	15:52:28.384988 +0100	TablePlus	Task <69BB5F40-14FC-464F-BF7A-2F5BFC0B201C>.<101> received response, status 200 content K
standard	15:52:28.385316 +0100	TablePlus	Task <69BB5F40-14FC-464F-BF7A-2F5BFC0B201C>.<101> response ended
standard	15:52:28.385559 +0100	TablePlus	Task <69BB5F40-14FC-464F-BF7A-2F5BFC0B201C>.<101> done using Connection 24
standard	15:52:34.230837 +0100	TablePlus	Task <19600BB5-6D87-499C-8707-C65664C3C153>.<102> resuming, QOS(0x9)
standard	15:52:34.231352 +0100	TablePlus	Task <19600BB5-6D87-499C-8707-C65664C3C153>.<102> {strength 1, tls 8, ct 0, sub 0, sig 0, ciphers 1, bundle 0, builtin 0}
standard	15:52:34.231727 +0100	TablePlus	Task <19600BB5-6D87-499C-8707-C65664C3C153>.<102> now using Connection 24
standard	15:52:34.232330 +0100	TablePlus	Task <19600BB5-6D87-499C-8707-C65664C3C153>.<102> sent request, body S
standard	15:52:34.332133 +0100	TablePlus	Task <19600BB5-6D87-499C-8707-C65664C3C153>.<102> received response, status 200 content K
standard	15:52:34.332389 +0100	TablePlus	Task <19600BB5-6D87-499C-8707-C65664C3C153>.<102> response ended
standard	15:52:34.332569 +0100	TablePlus	Task <19600BB5-6D87-499C-8707-C65664C3C153>.<102> done using Connection 24
standard	15:53:04.982201 +0100	TablePlus	TIC TCP Conn Event [24:0x600002372880]: 2
standard	15:53:04.982285 +0100	TablePlus	TIC TCP Conn Cancel [24:0x600002372880]
standard	15:53:04.982588 +0100	TablePlus	[C24 Hostname#c61e2d6a:443 tcp, url: https://e.crashlytics.com/spi/v2/events, tls, no cellular] cancel
standard	15:53:04.982867 +0100	TablePlus	[C24 Hostname#c61e2d6a:443 tcp, url: https://e.crashlytics.com/spi/v2/events, tls, no cellular] cancelled
	[C24.1 <private> 192.168.1.43:53186<->IPv4#bf54582d:443]
	Connected Path: satisfied (Path is satisfied), interface: en9, ipv4, dns
	Duration: 37.058s, DNS @0.000s took 0.018s, TCP @0.025s took 0.098s, TLS took 0.235s
	bytes in/out: 6207/3713, packets in/out: 9/6, rtt: 0.096s, retransmitted packets: 0, out-of-order packets: 0
standard	15:53:04.982948 +0100	TablePlus	0.000s [C24 <private> Hostname#c61e2d6a:443 resolver] path:start
standard	15:53:04.983014 +0100	TablePlus	0.000s [C24 <private> Hostname#c61e2d6a:443 resolver] path:satisfied
standard	15:53:04.983075 +0100	TablePlus	0.000s [C24 <private> Hostname#c61e2d6a:443 resolver] resolver:start_dns
standard	15:53:04.983131 +0100	TablePlus	0.018s [C24 <private> Hostname#c61e2d6a:443 resolver] resolver:receive_dns
standard	15:53:04.983199 +0100	TablePlus	0.021s [C24.1 <private> 192.168.1.43:53186<->IPv4#bf54582d:443 socket-flow] path:start
standard	15:53:04.983266 +0100	TablePlus	0.022s [C24.1 <private> 192.168.1.43:53186<->IPv4#bf54582d:443 socket-flow] path:satisfied
standard	15:53:04.983327 +0100	TablePlus	0.025s [C24.1 <private> 192.168.1.43:53186<->IPv4#bf54582d:443 socket-flow] flow:start_connect
standard	15:53:04.983386 +0100	TablePlus	0.123s [C24.1 <private> 192.168.1.43:53186<->IPv4#bf54582d:443 socket-flow] flow:finish_transport
standard	15:53:04.983444 +0100	TablePlus	0.123s [C24 <private> Hostname#c61e2d6a:443 resolver] flow:finish_transport
standard	15:53:04.983506 +0100	TablePlus	0.358s [C24.1 <private> 192.168.1.43:53186<->IPv4#bf54582d:443 socket-flow] flow:finish_connect
standard	15:53:04.983567 +0100	TablePlus	0.358s [C24 <private> Hostname#c61e2d6a:443 resolver] flow:finish_connect
standard	15:53:04.983633 +0100	TablePlus	0.358s [C24.1 <private> 192.168.1.43:53186<->IPv4#bf54582d:443 socket-flow] flow:changed_viability
standard	15:53:04.983779 +0100	TablePlus	0.359s [C24 <private> Hostname#c61e2d6a:443 resolver] flow:changed_viability
standard	15:53:04.983915 +0100	TablePlus	37.058s [C24] path:cancel
standard	15:53:04.985071 +0100	TablePlus	nw_endpoint_flow_protocol_disconnected [C24.1 IPv4#bf54582d:443 cancelled socket-flow (null)] Output protocol disconnected
standard	15:53:04.986775 +0100	TablePlus	nw_connection_report_state_with_handler_locked [C24] reporting state cancelled
standard	15:53:04.986838 +0100	TablePlus	TIC TCP Conn Destroyed [24:0x600002372880]
```

**Comment by huyphams** [comment] 2018-11-30 09:17
Hi @dennisirmscher 
1. the button "Test" remains grayed out. When trying to connect, TablePlus hangs at "Connecting to database..." => Because TablePlus still trying to connect to the server.
2. I will try to reproduce the bug and get back to you.

**Comment by dennisirmscher** [comment] 2018-11-30 10:12
Thank's for your feedback. If I can be of any help reproducing the bug, you are welcome to get in touch with me.

**Comment by dennisirmscher** [comment] 2018-12-11 09:14
@huyphams Were you able to reproduce the problem? The bug still occurs with me, even in the latest version that was released recently.

**Comment by dennisirmscher** [comment] 2019-01-02 11:01
Hey @huyphams, yes, I can confirm it's working with build 146. I will stick with this until you were able to find and fix the issue. Thank you for your work!

**Comment by dennisirmscher** [comment] 2019-01-16 17:02
Hey @huyphams, the bug seems to be fixed with build 176. Thank you!

**Comment by huyphams** [comment] 2019-01-17 12:42
It looks like it was resolved. So I will close this issue.
Please let me know if anyone still facing this issue.
Thanks all.

**Closed by huyphams** 2019-01-17 12:42 UTC
Labels: bug, done

**Comment by prasad1508** [comment] 2019-06-21 16:45
hi, I had the same problem, but it goes away after typing host as 127.0.0.1    I connected to Mysql DB

**Comment by mehrancodes** [comment] 2020-07-17 12:53
I have changed the host to 127.0.0.1 but it's still not connecting to the DB, what else could I test?

![Screen Shot 2020-07-17 at 5 22 09 PM](https://user-images.githubusercontent.com/7046255/87788198-33ca7080-c852-11ea-923e-1b89279f75a7.png)

**Comment by iMezied** [comment] 2020-09-07 07:51
@mehrancodes I solved this by leave host and port empty
