### ISSUE TITLE
import from csv doesn't work as expected

### ISSUE THREAD

**Issue by aramhovsepyan** [TablePlus/TablePlus#804] opened 2018-11-17 13:59 UTC
Import from CSV doesn't work in an existing table. When I import it in a new table and simply copy all rows as an insert statement it works just fine.

**Comment by huyphams** [comment] 2018-11-17 16:11
Hi @aramhovsepyan which TablePlus build are you using? Which database and how to reproduce the issue? I can’t fix it because I can’t reproduce it.

**Comment by aramhovsepyan** [comment] 2018-11-18 10:44
Hi @huyphams,
Indeed I should have been more specific. 
I am using TP version 1.0 (156)
It's a postgresql database (v 10.5)
The csv import does work, but all string fields remain null. If this is not enough I can provide you with a .csv file example.
Regards

**Comment by huyphams** [comment] 2018-11-18 11:02
Hi @aramhovsepyan thanks for the details, it would be great if you can send me an example via email: huy@tableplusapp.com i think this bug related to encoding, but not for sure.

**Comment by JohnRomanski** [comment] 2018-12-07 17:32
I don't know if this is related, but i can't seem to import a CSV into MySQL 5.7 that has null values for date fields.

**Comment by JeppeKnockaert** [comment] 2018-12-18 14:09
I'm having the same issue as @JohnRomanski

**Comment by JohnRomanski** [comment] 2018-12-18 14:57
My solution has been to drop back into the command line for this step in my process. You have to use a flag to enable the abilities to load from data files.

**Comment by huyphams** [comment] 2018-12-18 15:02
Can you give me an example table creation/CSV @JeppeKnockaert thank you so much!

**Comment by JeppeKnockaert** [comment] 2018-12-18 15:14
I've created a minimal reproducible case:

### Table creation
```
CREATE TABLE `test` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`));
```

### Insert statement
```
INSERT INTO `test` (`id`, `created_at`) VALUES ('1', NULL);
```

### CSV
```
"id","created_at"

1,
```

Importing that CSV (exported in Tableplus based on the above insert statement) gives an error:

<img width="820" alt="screenshot 2018-12-18 at 16 11 21" src="https://user-images.githubusercontent.com/1913807/50163086-00270d80-02e0-11e9-8ae7-f2276a4b4d3f.png">

**Comment by huyphams** [comment] 2018-12-18 17:47
Hi thanks all, 
it should work now: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
It will be included in the next release 168. You guy can use this build until then.

**Comment by huyphams** [comment] 2018-12-18 17:48
cc @JohnRomanski and @JeppeKnockaert thank you!

**Comment by JeppeKnockaert** [comment] 2018-12-19 08:06
Thanks for the quick solution!

**Comment by JohnRomanski** [comment] 2018-12-19 18:40
Yes, I can confirm that the build you provided fixes the problem that I had!

**Closed** 2018-12-30 08:36 UTC
Labels: done, enhancement

**Comment by AdleyRCI** [comment] 2020-10-12 10:02
The build 168 is not deployed for Windows version? I have the same bug, I can't import a CSV file. My build version is 142.

**Comment by huyphams** [comment] 2020-10-12 10:05
Hi @AdleyRCI it's macOS build, the Windows repo is here: https://github.com/TablePlus/TablePlus-Windows/issues and the 142 is the newest release. Do you have any screenshot or step to reproduce the issue?

**Comment by AdleyRCI** [comment] 2020-10-12 10:49
Hi, 
When I whant to import a CSV file, I have this error message without any further informations. 

![image](https://user-images.githubusercontent.com/72453399/95738345-5cafa580-0c89-11eb-8629-f7c91451b7e0.png)

**Comment by huyphams** [comment] 2020-10-12 10:55
You can toggle the console to see the table creation (control + shift + C). I think there was a syntax error.
