### ISSUE TITLE
Redis Connection over SSL support

### ISSUE THREAD

**Issue by vaseems** [TablePlus/TablePlus#769] opened 2018-11-01 02:58 UTC
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Redis

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 1.0 (146)
3. The steps to reproduce this issue:
We have a azure redis instance which provides option to connect via SSL only. I couldn't connect to it because there is no such option in tableplus.

**Comment by saswatds** [comment] 2019-02-08 05:56
AWS ElasticCache redis also has the SSL only option so need the feature to connect to them

**Comment by huyphams** [comment] 2019-02-11 05:25
It's duplicated: https://github.com/TablePlus/TablePlus/issues/652
We will support it asap. The problem is the official driver is not support it and the PR is not merged.
https://github.com/redis/hiredis/pull/570

**Comment by benjoz** [comment] 2019-02-22 12:48
@huyphams https://github.com/redis/hiredis/pull/570 is closed but https://github.com/redis/hiredis/pull/645 is already merged. 

Any chance to have SSL support on Redis soon ? I would love to have a try :)

**Comment by huyphams** [comment] 2019-02-22 12:49
Great news, i will try to implement it tonight!

**Comment by huyphams** [comment] 2019-02-22 16:33
I added but I'm not sure why I can't connect to Elasticache using SSL.
I got this error
```
ST(0x1001). unknown state. R(0x1)U
ST(0x4008). unknown state. R(0x230)F
ST(0x1002). error. R(0xffffffff)U
ST(0x1002). error. R(0xffffffff)U
```
I will report to Hiredis tomorrow.

**Closed** 2019-06-20 16:49 UTC
Labels: duplicate
