### ISSUE TITLE
Option to display labels instead of DB name on left bar

### ISSUE THREAD

**Issue by gabrielrinaldi** [TablePlus/TablePlus#735] opened 2018-10-22 21:09 UTC
I would like an option to display labels on the left tab bar instead of the name of the database that I am connected to. 

The reason for that is that in some SaaS providers like Heroku the DB name is not something you can easily recognize: 
![image](https://user-images.githubusercontent.com/38957/47319659-1bd5a680-d604-11e8-8db4-81c82215344b.png)

**Comment by alvint** [comment] 2018-10-23 13:48
Duplicate of issue #723.

**Closed** 2019-06-20 16:45 UTC
Labels: enhancement
