### ISSUE TITLE
[Feature Request] Add support for YugabyteDB

### ISSUE THREAD

**Issue by Sfurti-yb** [TablePlus/TablePlus#3227] opened 2024-02-22 04:26 UTC
[YugabyteDB](https://docs.yugabyte.com/) is distributed PostgreSQL that delivers on-demand scale, built-in resilience, flexible geo-distribution, and a multi-API (PostgreSQL-compatible and Cassandra-inspired) interface to power business-critical applications.
YugabyteDB YCQL API (Cassandra-inspired) supports jsonb columns and while loading the tables containing a jsonb column we get a request timed out error. The (YugabyteDB driver)[https://github.com/yugabyte/cassandra-java-driver] can handle support for jsonb columns as well.
Please let us know what are the steps to get YugabyteDB added as a database in TablePlus. Thanks!

**Comment by huyphams** [comment] 2024-03-12 06:15
Hi @Sfurti-yb I'm not sure how to reproduce the issue. I can load the jsonb column just fine.
<img width="1185" alt="Screenshot 2024-03-12 at 1 13 54 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/c8116258-244c-414d-8603-e3d88b338e6c">

**Comment by huyphams** [comment] 2024-03-12 06:15
Please don't remove our issue template questions.

**Comment by ckamaleo** [comment] 2024-03-14 19:16
@huyphams The issue is with using Cassandra Driver available in Tableplus. 

We were able to repro this internally:

Table 1:
```
CREATE TABLE eis_api.books (
    id int PRIMARY KEY,
    details jsonb
) WITH default_time_to_live = 0
    AND transactions = {'enabled': 'false'};
```
When loading this table in TablePlus, we see an error Request timed out.

Table 2:

```
CREATE TABLE eis_api.books2 (
    id int PRIMARY KEY,
    details TEXT
) WITH default_time_to_live = 0
    AND transactions = {'enabled': 'false'};
```
When loading this table in TablePlus, we do not see any error.
This problem is related to the Cassandra driver not supporting JSONB datatype, Yugabyte drivers for CQL supports JSONB. So we need to add Support for Yugabyte's Cassandra Driver in Tableplus.

**Comment by huyphams** [comment] 2024-03-14 19:25
Ah okie, I'm testing with the Postges protocol

**Comment by huyphams** [comment] 2024-03-17 05:38
The issue is inside the Cassandra native driver. If TablePlus wants to support jsonb, we would modify the native cassandra driver (customize), May I ask why the user didn't use the PostgreSQL protocol but Cassandra, which does not support jsob?

**Comment by huyphams** [comment] 2024-03-17 17:22
We added support it, it will be included in the next update!

**Comment by ckamaleo** [comment] 2024-03-18 14:32
@huyphams Thank you, Any ETA on the next release with the Yugabyte YCQL Driver Support?

**Comment by huyphams** [comment] 2024-03-18 14:39
Within this month @ckamaleo thanks

**Closed** 2024-03-26 04:01 UTC

**Comment by ckamaleo** [comment] 2024-03-28 18:29
@huyphams Few quick questions. 
Would yugabyte driver be part of the UI? 
Also are you planning to include the Yugbayte's YCQL java driver listed here? https://docs.yugabyte.com/preview/reference/drivers/ycql-client-drivers/#yugabytedb-java-driver-for-ycql-3-10

**Comment by ckamaleo** [comment] 2024-04-02 17:33
@huyphams Just wanted to followup on the above and also if the new tableplus version is released?

**Comment by huyphams** [comment] 2024-04-02 17:35
Yep it is released on the newest TablePlus macOS update

**Comment by ckamaleo** [comment] 2024-04-02 17:39
@huyphams  Looks Build 542 has the driver included, I downloaded the latest version but I am not seeing the YCQL Yugabyte Driver - https://tableplus.com/blog/2017/02/changelogs.html

Can you please check and advise?

**Comment by ckamaleo** [comment] 2024-04-02 17:40
<img width="606" alt="Screenshot 2024-04-02 at 12 40 29 PM" src="https://github.com/TablePlus/TablePlus/assets/58093306/0339dd59-b828-49fe-ae03-ad495e6461f3">

**Comment by ckamaleo** [comment] 2024-04-03 16:12
@huyphams Just wanted to followup on the above. Can you please check and advise?

**Comment by huyphams** [comment] 2024-04-04 05:10
Hi @ckamaleo we did not split it to a new library. So you can use the Cassandra to get the same result. We may separate it to a new driver next release.
