### ISSUE TITLE
Add support for Oracle

### ISSUE THREAD

**Issue by timster** [TablePlus/TablePlus#226] opened 2018-02-09 16:23 UTC
I just read on the homepage it says coming soon, so please close this if it's not necessary.

**Comment by alvint** [comment] 2018-06-11 16:02
Hi, is there an ETA for Oracle support? I'm looking for an excuse to buy this. :)

**Comment by huyphams** [comment] 2018-06-11 16:05
Hey @alvint we're planing to support it in July.

**Comment by alvint** [comment] 2018-06-11 16:08
Thanks, buying it now! If you need someone to help beta test a version with Oracle support, let me know. I've been a developer for 30+ years so my feedback may be useful.

-Alvin

**Comment by huyphams** [comment] 2018-06-11 16:12
Sure @alvint i'm surely to update this thread when it's ready.

**Comment by alvint** [comment] 2018-07-02 14:12
Cool! A few notes so far:

- when creating a connection, the field labeled "database" is where you need to put the service name/SID which may be confusing to some people
- the table structure isn't shown (i assume it's not implemented yet)
- when looking at table data, columns of type `date` are shown as null

**Comment by bvanderhaar** [comment] 2018-07-02 18:19
I'll add one more:
SqlDeveloper usually only pulls the first 50/100/etc rows, which is nice (and Oracle's syntax for Top N is odd compared to sql server).  Would be nice to do that or have an option for this since I'm usually using an app like this to just get a feel for the data (and many tables are millions of rows).

The speed of both autocomplete, retrieving records and the UI is blistering fast compared to sqldeveloper - really awesome.  I will probably have an easy time convincing the bosses to buy this once Oracle is integrated.  Thanks!

**Comment by bvanderhaar** [comment] 2018-07-02 18:21
Just tried to add a where clause to a sql query and it crashes after I type the character w

**Comment by huyphams** [comment] 2018-07-03 09:52
Hi all @timster @alvint @bvanderhaar , I just update the build here: https://www.dropbox.com/s/dcr03jxjr1gnqck/TablePlus.zip?dl=0
Change:
- Simplify the Create new Connection form.
- Support estimate rows (TablePlus will estimate rows instead of count(*) while loading a large table).
- Load basic table structure and index.
- Support edit inline, insert rows.
Some small improvements.

**Comment by bvanderhaar** [comment] 2018-07-05 13:30
The where clause bug is fixed.  But I did load a 1M+ result set that crashed the app - going to have to get used to rownum limiting the results ;).  Here a more comprehensive guide on how to limit results - https://stackoverflow.com/questions/470542/how-do-i-limit-the-number-of-rows-returned-by-an-oracle-query-after-ordering
It'd be nice to be built-in, but probably not a deal-breaker.

Let me know if there is other feedback you need.

**Comment by f0ntana** [comment] 2018-07-14 04:46
hi, this version support procedure and triggers on trial or only if pay?

**Comment by huyphams** [comment] 2018-07-14 04:47
Are you asking about Oracle? @f0ntana 
The Oracle is not done yet (include trigger and procedure, view...)

**Comment by f0ntana** [comment] 2018-07-14 04:50
That's right, I'm interested, do you have any idea of the deadline?

**Comment by huyphams** [comment] 2018-07-14 04:55
I don't have a deadline but I can add support trigger, procedure, view... and some other improvements for this build in this week.
I always keep the beta build up to date with the master (the release branch).

**Comment by f0ntana** [comment] 2018-07-14 05:07
Amazing, if you add this features, certainly I want this App, I will wait for this. Thanks

**Comment by f0ntana** [comment] 2018-07-18 21:16
The app updated and now I can't use oracle?

Version 1.0(116)

**Comment by huyphams** [comment] 2018-07-19 01:32
Hey @f0ntana it was merged to master, I just updated the beta build to 116, You can download it here: https://www.dropbox.com/s/dcr03jxjr1gnqck/TablePlus.zip?dl=0

**Comment by f0ntana** [comment] 2018-07-19 11:59
@huyphams thanks

**Comment by f0ntana** [comment] 2018-07-19 12:08
@huyphams thanks
This version has functions and procedures.. its amazing.. 
maybe will you separate the views of tables?
eager for future functionality..

I can't edit this views? 

thanks a lot!

**Comment by whyhankee** [comment] 2018-07-19 14:13
Also using the Beta for Oracle I notice that the reconnect recovery does not seem to work as nice as the other db types. I really need to close the window and reconnect .. Not a really big thing, but anyway.

(thanks for writing this amazing peace of software, bought it of course)

**Comment by huyphams** [comment] 2018-07-20 09:03
@f0ntana yup, I'm still optimizing it. I wonder if people want to display all tables in all_tables or only tables in user_tables?
@whyhankee are you using SSH to connect to the server?

**Comment by whyhankee** [comment] 2018-07-20 10:33
@huyphams regarding reconnect: no, I'm locally connected to a docker-container on my Mac

**Comment by f0ntana** [comment] 2018-07-20 13:18
@huyphams all programs that I had used display all separates, like this.

![screen shot 2018-07-20 at 09 17 55](https://user-images.githubusercontent.com/6570783/43004465-dcee395a-8bfd-11e8-8d85-273a390c6496.png)

**Comment by alvint** [comment] 2018-07-20 13:20
@huyphams I have a similar issue as @whyhankee, except I'm using an SSH tunnel that isn't configured through TablePlus (in TP it appears I'm connecting to localhost). If the tunnel disconnects, even if I bring it back up immediately TP needs to be restarted. Would this be more reliable if I used the "over SSH" feature?

**Comment by huyphams** [comment] 2018-07-20 14:32
Hmm, I'm not sure, let me try to reproduce it.

**Comment by netinhoteixeira** [comment] 2018-07-21 18:18
Please, 1+ to test it. I have another tools but I luv to use one native, all are in Java and they are sooo heavy.

**Comment by f0ntana** [comment] 2018-07-30 14:53
@huyphams I make the update and oracle don't work.. can u send new link ?

thanks

**Comment by huyphams** [comment] 2018-07-30 14:56
It's the same link above, I always upload the new build on Dropbox after release. It's sync everywhere.

**Comment by f0ntana** [comment] 2018-07-30 14:59
ohh ok 🎉

**Comment by f0ntana** [comment] 2018-07-30 17:35
@huyphams are you working on procedures and triggers?

**Comment by f0ntana** [comment] 2018-08-01 15:07
hey.. I had a problem, when table has many rows, and I run a command, and cancel the query, the app broken and send Unexpected.

**Comment by huyphams** [comment] 2018-08-01 15:08
Thanks @f0ntana , I will check it.
About the trigger and procedures, I'm working on it.

**Comment by huyphams** [comment] 2018-08-27 02:41
Hi guys, I will release a nightly build with auto update. Now, we don't need to download manually every time a new update released.
A nightly build includes Oracle support. I will update this thread when it ready, this week.

**Comment by alvint** [comment] 2018-08-28 19:33
Just an annoying reminder that columns of type `timestamp` are still shown as null...

**Comment by huyphams** [comment] 2018-08-29 02:59
No @alvint because I will fix it now and update the build :D

**Comment by huyphams** [comment] 2018-08-29 05:37
Well, I discovered that I forgot to put `break;` in the switch statement, this statement parses rows in Oracle.
Probably, because I code Swift too much :(
All fixed: https://www.dropbox.com/s/dcr03jxjr1gnqck/TablePlus.zip?dl=0

**Comment by alvint** [comment] 2018-08-29 15:17
Cool, that worked. Thanks!

**Comment by alvint** [comment] 2018-08-29 16:58
Whoops, the offset still isn't being displayed. For example, `select timestamp '2018-08-21 10:00:00 +04:00' from dual`:

<img width="268" alt="image" src="https://user-images.githubusercontent.com/622202/44802934-00619880-ab8b-11e8-847a-1b47fd7b1179.png">

How it should be:

<img width="336" alt="image" src="https://user-images.githubusercontent.com/622202/44802743-84ffe700-ab8a-11e8-9457-ac5e93244242.png">

This is unrelated, but if the year were at the beginning then the current column sorting would also (mostly) work for dates without additional development effort...  :)

**Comment by alvint** [comment] 2018-08-29 16:59
@huyphams ^^

**Comment by huyphams** [comment] 2018-08-30 04:28
Yeah @alvint, TablePlus uses format `DD-MM-YYYY HH24:MI:SS:FF3` I will change it to support offset.

**Comment by spruce** [comment] 2018-08-30 09:43
I don't know if I just can't find it or if it is not present but what about Views? In our project we heavily depend on Views.

**Comment by alvint** [comment] 2018-08-30 16:49
@spruce The views are listed with the tables. I don't think showing/changing the SQL for the view is implemented yet.

**Comment by huyphams** [comment] 2018-09-01 08:48
I just figured out this bug: https://github.com/TablePlus/TablePlus/issues/226#issuecomment-406290576
It will be fixed in the next update.

**Comment by huyphams** [comment] 2018-09-07 15:26
Hey @brianalois please press: `cmd + ,` and turn on
<img width="612" alt="nice" src="https://user-images.githubusercontent.com/3654622/45228306-07a44700-b2ed-11e8-9e0b-88ff1505bdb8.png">
Then check for update, that build supports Oracle. 👍

**Comment by brianalois** [comment] 2018-09-07 15:29
I have done that nad gives me this error. 

Error: ORA-24454: client host name is not set

**Comment by huyphams** [comment] 2018-09-07 15:30
Hey, can you reach me on email huy@tableplusapp.com with a screenshot of your setup?

**Comment by ccakes** [comment] 2018-09-18 19:14
Same issue as @brianalois - was there a simple solution?

**Comment by f0ntana** [comment] 2018-09-18 19:17
here no problems i had connected on multiples with no problems, 

Build 129.

**Comment by ccakes** [comment] 2018-09-19 08:12
Ok - a bit of digging resolved this. Somehow I was missing some of the default entries in `/etc/hosts` and so my hostname wouldn't resolve locally.

Fixed this and TablePlus is working fine 👍 Apologies for the noise.

**Comment by huyphams** [comment] 2018-09-21 12:01
FYI: Maybe, you guys have faced a crash bug that happens when TablePlus try to reconnect. This is one of know issue and it related to the Oracle library OCI: https://github.com/vrogier/ocilib/
I can reproduce it but can't fix because it was distributed as a dynamic library.
I will try to integrate all code and try to debug it next time, Hope I can fix this annoying bug. 

@alvint maybe the one who has a lot of crash due to this issue.

@f0ntana sorry, I didn't complete it, the crash bug has a higher priority. I have tried to get table triggers but I take too long (I need to optimize it to make sure it won't hit the performance).

**Comment by alvint** [comment] 2018-09-21 16:09
@huyphams Yep, but I haven't seen many crashes in recent builds (just one in the last couple of weeks I think).

**Comment by f0ntana** [comment] 2018-10-25 13:53
Some updates for oracle users?

**Comment by lamak** [comment] 2018-11-14 04:46
@huyphams 
I'm trying to connect Cyrillic win1251 database and got ? instead of Cyrillic characters. That seems to be AL16UTF16 used by default.
Trying to set NLS_LANG to RUSSIAN_CIS.CL8MSWIN1251 (that works on windows machines) — things get worst.
Here is NLS_DATABASE_PARAMETERS:
<img width="466" alt="screenshot 2018-11-14 at 14 41 19" src="https://user-images.githubusercontent.com/795844/48460652-bef09900-e81b-11e8-9384-3ccaf1943ad2.png">

**Comment by huyphams** [comment] 2018-11-14 04:48
This is one of the know issues, working with encoding in Oracle is not as easy as other drivers. Please wait for the next release.

**Comment by lamak** [comment] 2018-11-14 04:49
Thanks for quick reply, I'll be waiting

**Comment by jwill824** [comment] 2019-01-04 15:34
Hi @huyphams , I'm testing TablePlus out for the company/enterprise I work for. We deal mostly with Oracle stored data. When trying to connect I get the following error:

> Error: ORA-28011: the account will expire soon; change your password now

And then the connection is disrupted. ORA-28011 is the correct error code I'd expect. Our DBAs have to rotate our passwords. But this shouldn't be a "connection failure" error, should it? I'd expect for the TablePlus to notify and then continue the connection.

Is this an expected result? Or maybe even an issue with the version of TablePlus I have?

**Comment by huyphams** [comment] 2019-01-04 15:35
Hi @jwill824 I'm not sure, let me check it and reply to you.

**Comment by jwill824** [comment] 2019-01-04 15:39
Much appreciated, @huyphams ! Let me know if you need more information.

**Comment by huyphams** [comment] 2019-01-04 17:09
Hi @jwill824 it looks like an Oracle user issues, here I found:
From Oracle forum:
-  https://community.oracle.com/thread/2514892

And some other sites:
- http://www.dba-oracle.com/t_ora_28011.htm
- https://helpdbas.wordpress.com/2014/07/16/failed-to-connect-to-database-ora-28011-the-account-will-expire-soon-change-your-password-now/

**Comment by huyphams** [comment] 2019-01-18 09:01
Good news, the crash bug seems to be fixed on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
cc @alvint @f0ntana 

Next Cyrillic characters bug!

**Comment by rohitsrivatsav** [comment] 2019-01-31 17:53
How do i view and execute stored procedures ?

**Comment by marius-kildedal** [comment] 2019-02-04 11:41
Any tips on logging on with connection type TNS
<img width="790" alt="screenshot 2019-01-24 at 11 13 46" src="https://user-images.githubusercontent.com/44087608/52206328-2990fe00-287a-11e9-9323-90d96153eda1.png">

**Comment by felipe-ff** [comment] 2019-02-06 18:32
Can we expect to use Oracle with windows on TablePlus soon?

**Comment by ahmadarif** [comment] 2019-03-25 08:49
Hi, i've purchased this awesome tools.
I tried connecting to Oracle, but it took too long, it takes about 5 minutes. if using dbeaver, it's connect normally.

![image](https://user-images.githubusercontent.com/10185374/54906302-925d3400-4f15-11e9-804e-f91342f2be06.png)

**Comment by huyphams** [comment] 2019-03-25 09:23
Hi @ahmadarif TablePlus will load all tables, views, functions at startup but DBeaver only loads it when needed.
Have you disabled the function section and try again? I will find a way to optimize it.
<img width="633" alt="Screen Shot 2019-03-25 at 4 22 26 PM" src="https://user-images.githubusercontent.com/3654622/54908333-3a74fc00-4f1a-11e9-9b48-58c21095105e.png">

**Comment by ahmadarif** [comment] 2019-04-03 10:37
Sorry @huyphams , I missed this notification.
Where is the setting located?

**Comment by huyphams** [comment] 2019-04-03 10:42
it's in the workspace @ahmadarif , at the bottom left.

**Comment by ahmadarif** [comment] 2019-04-03 11:00
my settings are the same as yours @huyphams 
But still needed more time to open oracle workspace :(

**Comment by RyanSnodgrass** [comment] 2019-04-05 15:33
Hi, I'm getting the same issue as @ahmadarif. I set up my oracle connection and then it told me to download the beta version and directed me to this issue thread. Then it sat on the Connecting to database... page for longer than 5 minutes. I'm not able to get connected to Oracle.
I'm on version 2.2 (212) on Mac High Sierra 10.13.6

**Comment by huyphams** [comment] 2019-04-05 15:44
You must enable beta build and check for update again @RyanSnodgrass 
<img width="612" alt="beta" src="https://user-images.githubusercontent.com/3654622/55639782-63d43880-57f4-11e9-8fce-97e2df6ef352.png">

**Comment by MTProgramming** [comment] 2019-07-11 18:34
Getting this error when trying to update to beta version on:

OSX Catalina and build 242-> 244

<img width="419" alt="Screen Shot 2019-07-11 at 2 33 36 PM" src="https://user-images.githubusercontent.com/52469526/61075929-0817dd80-a3e9-11e9-9854-01afb2398406.png">

**Comment by brianschardt** [comment] 2019-08-19 13:05
@huyphams I got oracle working on the old version. But i just got a new computer and downloaded it again and turned on Beta updates but it cannot connect to an oracle database. When I try it says Do you want to download the build which supoort Oracle. I then click the Download button. Then nothing happens. 

Can you please help me with this.

**Comment by huyphams** [comment] 2019-08-20 02:17
hey @lamak TablePlus now support UTF8, if you have a chance, please try this build:
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
<img width="1189" alt="utf8" src="https://user-images.githubusercontent.com/3654622/63312293-72b91480-c2d7-11e9-87e4-6d8679d34f90.png">

**Comment by lamak** [comment] 2019-08-22 04:00
@huyphams, thanks that works!
Viewing, quering is fine, but error messages ORA also converted to another charset, look 
![Screenshot 2019-08-22 at 13 36 40](https://user-images.githubusercontent.com/795844/63485009-13c8ea80-c4e5-11e9-9edb-1c956c3b7b21.png)

**Comment by huyphams** [comment] 2019-08-22 04:17
Hey @lamak thanks for confirming, could you please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 
and let me know the result?

**Comment by lamak** [comment] 2019-08-22 04:27
@huyphams and this is great! error message is shown in my language (translated). Problem is solved.

**Comment by clodal** [comment] 2019-08-22 05:49
Hi guys, i'm running TablePlus 2.8.2 on MacOS Catalina Beta 6. Facing encoding issues in my OracleDB connection. Is it related to this issue?

<img width="272" alt="Screenshot 2019-08-22 at 1 48 22 PM" src="https://user-images.githubusercontent.com/8684825/63489038-8df86f80-c4e3-11e9-997c-c8d535e2b587.png">

**Comment by huyphams** [comment] 2019-08-22 11:28
@clodal Please go to Main menu Connection > View Using Encoding -> UTF8 and the restart the app.

**Comment by clodal** [comment] 2019-08-22 23:28
@huyphams Thanks for responding. As mentioned earlier I have already tried using all the encodings and restarted the app each time to no avail.

<img width="453" alt="Screenshot 2019-08-23 at 7 27 15 AM" src="https://user-images.githubusercontent.com/8684825/63556479-926e6800-c577-11e9-92a8-f97982761620.png">

**Comment by longnd** [comment] 2020-02-04 04:02
any updates regarding Oracle support ? :)

**Comment by kakawait** [comment] 2020-02-14 12:46
@huyphams links are KO could you please re-upload it?

**Comment by huyphams** [comment] 2020-02-14 13:04
By enabling the beta build, you will be able to update to the build that supports Oracle.
<img width="921" alt="abc" src="https://user-images.githubusercontent.com/3654622/74533856-20467100-4f65-11ea-8196-d311b41c011b.png">

**Comment by hskrasek** [comment] 2020-09-09 19:07
@huyphams Do you have any sense on if y'all are going to add OS Authentication to the Oracle connections

**Comment by poweredbyporkers** [comment] 2020-09-22 23:18
Any chance of Oracle working in the Windows version?

**Comment by digeomel** [comment] 2021-02-08 15:04
👍 for Oracle support in Windows.

**Comment by kczx3** [comment] 2021-05-05 18:47
So is Oracle support still in development/beta?  I assume we can't get Beta builds on the Trial version then?

**Comment by Sergio-P** [comment] 2021-07-22 21:39
Is there any apple silicon (M1) compatible build that support oracle?

**Comment by joranE** [comment] 2021-08-24 15:41
I would also love to know a time-table for Oracle support on Windows.

**Comment by floriskruisselbrink** [comment] 2023-09-08 09:27
Using TablePlus 5.4.0 on Silicon mac, it allows me to create a oracle connection, but when I try to connect to it, there is a popup that wants me to download  "the build which support Oracle".
![image](https://github.com/TablePlus/TablePlus/assets/936914/ea1e1549-e9c4-473a-9310-394f20ddfca3)

Clicking "Download" does nothing. Documentation on https://docs.tableplus.com states under supported databases "Oracle (Only macOS)".

So all information publically available seems to indicate it should work, but if I read this issue correctly this is not at all supported but only on Intel builds?? If so, is there anyway I can connect to Oracle using TablePlus? I don't see any solutions here or in the linked (closed) issues...

**Comment by huyphams** [comment] 2023-09-08 09:29
@floriskruisselbrink it does download the Oracle build and will show you an update popup when it is done. However, these are a "feature" of the sparkle (a lib that macOS use to make auto update) so please wait for a bit.

Unfortunately, you will need to run the TablePlus Oracle under rosetta as Oracle never release the ARM driver version.

**Comment by floriskruisselbrink** [comment] 2023-09-08 09:38
@huyphams thanks for the quick response! Until today I had no idea how to run anything "under rosetta". Just did that and tried it again.
Still not seeing any progress. Could it be a problem that my license expired 4 days ago? 🙈

**Comment by huyphams** [comment] 2023-09-26 21:07
I think I found away to connect Oracle natively on ARM without scarify the architect and the fat binaries. Will update asap.

**Comment by huyphams** [comment] 2023-09-27 15:34
Hi, we are working on a different product which support Oracle now, it's beta if you have a chance, please try it:
http://boltsql.com/

We may add it to TablePlus later if it works great on Bolt SQL.

**Closed by huyphams** 2023-09-27 15:34 UTC
Labels: new-feature

**Comment by prosavage** [comment] 2023-10-13 22:55
You should update the text for "download build which support oracle".
That is incorrect grammar.

**Comment by phjeltman** [comment] 2023-12-05 07:12
It's a bit odd to close a ticket for a product, with reference to a completely different product. Or is TablePlus going away?
