### ISSUE TITLE
Copy Rows As CSV should use empty separated comma values, instead of "null".

### ISSUE THREAD

**Issue by TheWriterAddict** [TablePlus/TablePlus#1043] opened 2019-03-12 23:16 UTC
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 11.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 200.

3. The steps to reproduce this issue:

Right click on row query result, on popup menu displayed, select "Copy rows as CSV", then paste on any place.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment] 2019-03-13 04:25
Hi @TheWriterAddict thanks for the feedback. it's fixed on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by chrschmitz** [comment] 2019-03-13 05:42
This works beautifully! However, now it is not possible anymore to distinguish between EMPTY and NULL if you paste rows back into TablePlus. Both previously EMPTY and NULL fields are now becoming NULL (which is better than EMPTY). Maybe you can add a preference "Copy / Paste NULL as empty field" or so.

**Comment by huyphams** [comment] 2019-03-13 05:45
It’s still working @chrschmitz because emtpy is “” and null is nothing btween two separator delimiters

**Comment by chrschmitz** [comment] 2019-03-13 05:52
I just realized a strange behavior. If you mark all rows of a table with Cmd-A and copy them with Cmd-C NULL fields are copied as NULL, if you choose Copy or Copy Rows As > CSV / CSV With Header NULL fields are copied as empty fields.

**Comment by chrschmitz** [comment] 2019-03-13 06:32
I created a video showing the weird behavior. The first copy is done with Cmd-A and Cmd-C (unfortunately I have no idea how to show the pressed keys).
[Screenrecording.mov.zip](https://github.com/TablePlus/TablePlus/files/2960039/Screenrecording.mov.zip)

**Comment by huyphams** [comment] 2019-03-13 07:06
Hi @chrschmitz the command + C is not a CSV. It was designed for internal copy/paste rows. but now, TablePlus can handle correctly NULL and EMPTY when copy/paste as CSV so I think I can union it.

**Comment by chrschmitz** [comment] 2019-03-13 08:26
I really like this! It is fantastic that the user has now both options (copy NULL as an empty string (with "Copy Rows as CSV") or copy NULL as NULL (with Cmd-C)). However, it is a little bit confusing that the keyboard shortcut does something else than the assigned menu entry. Anyhow, leave it as it is!

BTW: How can I set a VARCHAR field to NULL in TablePlus? When I delete the contents of a VARCHAR field, the field is set to EMPTY, when I delete the contents of an UNSIGNED INT field, the field is set to NULL. I was not able to not figure out, how to set a VARCHAR field to NULL and an UNSIGNED INT field to EMPTY.

**Comment by huyphams** [comment] 2019-03-13 08:28
You can do it easily by hold option + click on cell or using the right sidebar.

**Comment by chrschmitz** [comment] 2019-03-13 08:33
Option + click does not seem to work at that moment (see attached screenshot -- this is a VARCHAR field). The right sidebar does the job. That's awesome! Thanks!

![Screenshot](https://user-images.githubusercontent.com/13820940/54264240-eb6eb480-4572-11e9-80b4-ccfc37a2319f.jpg)

**Comment by huyphams** [comment] 2019-03-13 08:35
@chrschmitz it works if you're not in the editing mode (before entering the editing mode).

**Comment by chrschmitz** [comment] 2019-03-13 08:38
No, I tried that out as well (see attached screenshot). And how does TablePlus know, which field should be set to NULL or EMPTY. The field below the curser?

![Screenshot](https://user-images.githubusercontent.com/13820940/54264502-88c9e880-4573-11e9-915a-dfe2013df3e0.jpg)

**Comment by chrschmitz** [comment] 2019-03-13 08:40
But don't worry! It is fine if the field can be set to NULL / EMPTY or PRETTY (whatever that means) with the right sidebar.

**Comment by huyphams** [comment] 2019-03-13 08:40
I think it should be an option + left-mouse click, not the right mouse. Btw, we should use email because the comment is not related to the original post and it might annoy the author and people who are subscribing this repository 😄

**Closed** 2019-03-18 04:59 UTC
Labels: done, enhancement
