### ISSUE TITLE
[Feature Request] Please support Oracle on the Windows version

### ISSUE THREAD

**Issue by joranE** [TablePlus/TablePlus#2479] opened 2021-08-24 17:51 UTC
Elevating this from [this](https://github.com/TablePlus/TablePlus/issues/226#issuecomment-697031957) comment to it's own issue.

I would really appreciate Oracle support on the Windows version. I enthusiastically recommended TablePlus to a bunch of co-workers based on your website advertising a Windows version and simply listing a set of "supported databases", only to find that it was useless for them.

**Comment by huyphams** [comment] 2021-09-01 07:07
Duplicate of https://github.com/TablePlus/TablePlus-Windows/issues/182

**Closed by huyphams** 2021-09-01 07:07 UTC
