### ISSUE TITLE
MariaDB/MySQL tables with longtext fields load very slowly

### ISSUE THREAD

**Issue by leovalen** [TablePlus/TablePlus#2536] opened 2021-10-29 18:34 UTC
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
396

3. The steps to reproduce this issue:
- Load a table with longtext fields containing actually long texts (>1 kB)
- The table takes a very long time to load (> 10 seconds)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by esemlabel** [comment] 2022-03-28 12:08
I have similar issue with table having column either serialized or json encoded data of mediumtext type 5-10mb each.
It becomes dramatically slow to open table even when in contain only two rows.
I suggest to skip preloading medium and long text columns until preview was clicked by changing default "select *" to select every except those columns.

**Comment by StefanNeuser** [comment] 2022-04-24 23:09
Any solution on this, otherwise i need another DB tool! It's that much slower than sequel ACE

**Comment by leovalen** [comment] 2022-04-25 07:55
I had to switch to Sequel Ace for MariaDB due to this issue and import/export performance which is much better in Sequel Ace. Too bad for a commercial product not even acknowledging this issue.

**Comment by huyphams** [comment] 2022-04-25 10:45
Duplicate of https://github.com/TablePlus/TablePlus/issues/1261

**Closed by huyphams** 2022-04-25 10:45 UTC
