### ISSUE TITLE
Connection held open by TablePlus after closing window

### ISSUE THREAD

**Issue by dbkaplun** [TablePlus/TablePlus#399] opened 2018-04-28 13:26 UTC
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**PostgreSQL 10.3 on x86_64-apple-darwin17.3.0, compiled by Apple LLVM version 9.0.0 (clang-900.0.39.2), 64-bit**, installed via Homebrew

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**Version 1.0 (102)**

3. The steps to reproduce this issue:
    1. `createdb foo` in terminal
    2. Connect to the Postgres instance in TablePlus
    3. Connect to the database via `Show list database`
    3. Close all TablePlus windows while still keeping the application open in the Dock
    4. `dropdb foo` in terminal
    5. 
```
dropdb: database removal failed: ERROR:  database "foo" is being accessed by other users
DETAIL:  There is 1 other session using the database.
createdb: database creation failed: ERROR:  database "foo" already exists
```

*Also, it would be awesome if there was some way to copy the TablePlus version string!*

**Comment by huyphams** [comment] 2018-04-28 13:49
I can't reproduce the bug. I have checked the lasted version by this way:
Open TablePlus app -> Connect to a database.

Open terminal and run: `lsof -nPi | grep TablePlus` <- This command works fine on High Sierra. it will show you which Port TablePlus is using. 

- The result is:
<img width="875" alt="connection" src="https://user-images.githubusercontent.com/3654622/39397174-39c37a6a-4b25-11e8-8638-4a09d347b384.png">

If you connect over ssh you will see an ssh tunneling here.

After closing the workspace, all the connection is gone. (By check with the command above again).

It would be great if you can test with the step above to check out which process is using the connection.  I will investigate more. Thanks for the reporting.

**Comment by huyphams** [comment] 2018-04-28 15:57
Hmm, weird, I have tried twice and it's working. Sorry for the late response because I just back to home.
<img width="435" alt="screen shot 2018-04-28 at 10 56 39 pm" src="https://user-images.githubusercontent.com/3654622/39398403-76b5bb9c-4b37-11e8-9fcd-88776bb1219d.png">

**Comment by dbkaplun** [comment] 2018-04-28 18:42
Hey @huyphams,

I uploaded a repro: ![TablePlus #399 repro](https://user-images.githubusercontent.com/1765130/39399764-f6ae1a88-4af1-11e8-9359-e1629e49dfd3.gif)

Maybe something is different in my setup? I haven't changed much though.

**Comment by huyphams** [comment] 2018-04-29 01:44
Thank you so much, the video made sense. I have uploaded a build, can you check if it's working for you:
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by huyphams** [comment] 2018-05-03 07:50
It was fixed in release 103, so I close this issue.

**Closed by huyphams** 2018-05-03 07:50 UTC
Labels: bug, done

**Comment by dbkaplun** [comment] 2018-05-04 04:25
Thanks so much @huyphams!
