### ISSUE TITLE
Stored Procedure's output display incorrectly

### ISSUE THREAD

**Issue by vothanhkiet** [TablePlus/TablePlus#499] opened 2018-06-26 05:34 UTC
1. Which driver are you using and version of it:
RDS Microsoft SQL Server 2017 (RTM-CU3-GDR) (KB4052987) - 14.0.3015.40 (X64)
2. Which TablePlus build number are you using:
112
3. The steps to reproduce this issue:
Run Stored Procedure on TablePlus Query editor, the result display incorrectly. 
<img width="483" alt="screen shot 2018-06-26 at 12 24 48" src="https://user-images.githubusercontent.com/4302582/41891068-ce60ba1c-793c-11e8-8898-22f62e167010.png">

Compare to Microsoft SQL Server client for Node.js, version4.1.0
<img width="677" alt="screen shot 2018-06-26 at 12 24 03" src="https://user-images.githubusercontent.com/4302582/41891080-e1fc8c18-793c-11e8-8f9d-3c56e3c33d43.png">

**Comment by huyphams** [comment] 2018-06-26 07:59
Hey @vothanhkiet can you send me an example via email `huy@tableplusapp.com`. this bug is weird, I can't reproduce it with my database.

**Comment by vothanhkiet** [comment] 2018-06-26 15:18
Thos are from my customer's stored procedures, I can't access directly to the data source. Let me ask them to extract some records.

**Comment by huyphams** [comment] 2018-06-29 06:57
hey @vothanhkiet can you try this build and let me know the result? https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thanks.

**Comment by vothanhkiet** [comment] 2018-07-02 09:52
Hi there, I try your build, still got the same issue. I ask my customer to provide some sample data but that request was rejected, please put this issue on hold, I know that you have a lot of works to do. Thanks

**Comment by huyphams** [comment] 2018-08-16 08:50
Hi @vothanhkiet this build should fix your issue:
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
It will be released in the next update.

**Comment by vothanhkiet** [comment] 2018-08-16 09:02
Awesome, now I can see two different results at the same time. This issue is fixed

<img width="1005" alt="screen shot 2018-08-16 at 15 59 07" src="https://user-images.githubusercontent.com/4302582/44199110-6a327900-a16d-11e8-8f25-a9104f9d75cb.png">
<img width="995" alt="screen shot 2018-08-16 at 15 59 16" src="https://user-images.githubusercontent.com/4302582/44199112-6acb0f80-a16d-11e8-86f2-b406e8a449f4.png">

**Closed** 2018-08-17 06:08 UTC
Labels: bug, done
