### ISSUE TITLE
Time consuming and frequently refreshed schema discovery

### ISSUE THREAD

**Issue by markedmondson** [TablePlus/TablePlus#1963] opened 2020-06-19 21:23 UTC
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 11.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
320

3. The steps to reproduce this issue:
When you open a database with a lot of schemas (we have ~300), you then have to wait for TablePlus to cache the table columns for every schema before you can do anything, it's super expensive to watch it loop through all 300 schemas and x00 tables.

It'd be probably be preferred to have it trigger and index the current schema only when changing schema if possible.

Eg:
```sql
SELECT ordinal_position,column_name,udt_name AS data_type,numeric_precision,datetime_precision,numeric_scale,character_maximum_length AS data_length,is_nullable,column_name as check,column_name as check_constraint,column_default,column_name AS foreign_key,pg_catalog.col_description(7177143,ordinal_position) as comment FROM information_schema.columns WHERE table_name='tablename table_schema='schemaname';
```

**Comment by brianjsw** [comment] 2020-08-04 23:20
I can reproduce this issue on build 332 as well.  Using PostgreSQL 9.6. We have a multi-tenant database with hundreds of schemas each with the same tables in them.  I have had to stop using TablePlus because this issue interferes with typing SQL in the SQL window too much.  I can confirm the same query as the one markedmondson is reporting is the same issue I am seeing as well.  I never need to do cross-schema queries, so it sure would be nice if there was a way to limit the scope to a selected schema or something.   Thanks!

**Comment by huyphams** [comment] 2020-08-05 01:03
Thanks everybody, I'm working on this issue.

**Comment by markedmondson** [comment] 2021-03-04 19:54
Hey @huyphams any progress here? <3

**Comment by archonic** [comment] 2021-08-07 18:45
I'm in the same boat. I have a manageable wait at the moment but as I gain more customers, TablePlus becomes less and less a viable product.

**Comment by Jonnx** [comment] 2021-12-08 21:31
any updates on this issue? this issue makes redshift clusters almost completely unusable in TablePlus

**Comment by Ushmatar** [comment] 2022-06-23 10:14
This is a major issue and might force me to move away from TablePlus which I otherwise generally like. We have 100+ schemas and this greatly slows down development in Redshift.

**Comment by huyphams** [comment] 2022-06-23 10:16
Hi guys, please enable this option it will solve the issue. Maybe TablePlus should have suggested the user to enable it if there are more than 10 schemes
<img width="620" alt="Screen Shot 2022-06-23 at 5 15 40 PM" src="https://user-images.githubusercontent.com/3654622/175276324-efd1926e-8a0a-4e06-bbb6-a0bc9a14c83a.png">

**Comment by huyphams** [comment] 2022-06-23 14:31
I think this issue is resolved with the settings above. I will make it more discoverable in the next update.
Thanks

**Closed by huyphams** 2022-06-23 14:31 UTC
Labels: enhancement

**Comment by markedmondson** [comment] 2022-06-23 18:56
Thanks Henry <3

**Comment by markedmondson** [comment] 2022-06-23 20:00
Further question. Does this need enabling on every schema or does it switch on globally for the database? I'm guessing by the checked item it's the former but just confirming :)

**Comment by Ushmatar** [comment] 2022-06-23 21:19
Thanks a lot for the quick reaction and help! This solved the issue for me and I can keep being a happy TablePlus customer 🤩

**Comment by huyphams** [comment] 2022-06-24 01:30
Hi, @markedmondson it's per connection. You can enable it during setting up the connection or in the workspace.
<img width="732" alt="Screen Shot 2022-06-24 at 8 30 35 AM" src="https://user-images.githubusercontent.com/3654622/175441811-8b3ea1fb-b03e-40c2-8f41-3cb5f05b2782.png">

**Comment by jordan-brough** [comment] 2022-07-22 17:25
@huyphams is it possible to enable this option via a connection url?  i.e. `postgresql://...&lazyLoadSchemaItems=1`?

I have a script we use that reads connection information from 1Password and opens a connection in TablePlus and it'd be nice to be able to enable that via the URL.

**Comment by jrrbru** [comment] 2025-05-19 16:27
Is this still an option? I'm on Build 608, and I don't see the "Lazy load schema items" option...

**Comment by markedmondson** [comment] 2025-05-21 19:11
@jrrbru it's in here (608) - I did find recently that it wasn't working as expected but I didn't dig it further to verify.

![Image](https://github.com/user-attachments/assets/b9ace673-5485-4865-8c5e-13ea9d7797cb)

**Comment by jrrbru** [comment] 2025-05-21 19:19
> [@jrrbru](https://github.com/jrrbru) it's in here (608) - I did find recently that it wasn't working as expected but I didn't dig it further to verify.
> 
> ![Image](https://github.com/user-attachments/assets/b9ace673-5485-4865-8c5e-13ea9d7797cb)

I see it there now, thanks! It seems to be working so far.
