### ISSUE TITLE
Cancel Running SQL Is Not Working

### ISSUE THREAD

**Issue by xingtianyoulong** [TablePlus/TablePlus#783] opened 2018-11-06 08:41 UTC
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 5.x
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 150
3. The steps to reproduce this issue:
When I run a SQL，the result almost about 80000，If I click cancel button，the cancelling is processing and I can't do anything else，I should to waiting 10 minutes or more later...

[QQ20181106-163811-HD.mp4.zip](https://github.com/TablePlus/TablePlus/files/2552225/QQ20181106-163811-HD.mp4.zip)

**Comment by huyphams** [comment] 2018-11-06 08:51
There are two phases when executing a statement.
1. Submit a statement to the server and waiting for the response.
2. For-Loop fetches rows in the response.

Currently, TablePlus only supports cancel the query when it's on phase 2. Looks like your query is being stuck on phase 1.

**Comment by xingtianyoulong** [comment] 2018-11-06 09:06
@huyphams ，maybe you are right，but the same SQL on SQLyog，whenever I cancel the running SQL，it will stop and I can do other action later，not waiting and waiting.. please see attached files
[QQ20181106-170505-HD.mp4.zip](https://github.com/TablePlus/TablePlus/files/2552333/QQ20181106-170505-HD.mp4.zip)
.

**Comment by huyphams** [comment] 2018-11-06 09:07
Thanks @xingtianyoulong I will take a look and see how we can improve this feature.

**Comment by xingtianyoulong** [comment] 2018-11-06 09:12
@huyphams ，I like this software，especially the autocomplete speed & IDE speed，I will experience it more later，then I will buy your license and register it -_-

**Comment by hyperknot** [comment] 2019-03-01 03:01
This is a deal breaker for me, and actually questioning why did I purchase TablePlus. I regularly run long queries, and I need to be able to select them.

Currently the _only_ way to do it with TablePlus is to Quit the application and restart it. I cannot believe that a serious DB IDE doesn't allow cancelling a long query. Please fix this!

**Comment by soleares** [comment] 2019-06-05 02:56
This issue bit me yesterday and actually lead to a production slowdown. This was my fault of course for using a new tool that I didn't fully understand. But I assumed that when I cancelled a long running SQL query it would actually cancel it like it does in Sequel Pro.

Steps to reproduce:
- Run not properly indexed query.
- Hit cancel after ~30 secs.
- UI shows it's in progress cancelling.
- Wait 10+ minutes with no UI change.
- UI shows connection issue, but won't reconnect.
- Restart TablePlus
- Assume incorrectly that it's been cancelled, but it wasn't.

**Comment by huyphams** [comment] 2019-06-05 02:58
We're working on this issue, TablePlus canceling query will be resolved in the future releases (soon)
Concentp:
1. Press cancel => show the process list.
2. Choose the running query => kill.

**Comment by huyphams** [comment] 2019-06-06 05:38
TablePlus now can kill unresponsive query on MySQL
Download: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if anyone encounters any problems.

**Closed by huyphams** 2019-06-06 05:38 UTC

**Comment by manseuk** [comment] 2019-06-06 07:31
I have downloaded the update - thanks

I can confirm it works, however im not sure the way it works is the best - im given a popup with a list of running tasks that i can kill .... what happens if i click the wrong one ? the server i connect to has multiple queries running constantly - this is an accident waiting to happen. Is there no way to kill the actual query sent ?

**Comment by huyphams** [comment] 2019-06-06 07:33
TablePlus respect the safe mode, if you set the safe mode level is warning or prompt for the password, it will show you an alert before killing the query.
I'm working on an enhancement that TablePlus also will prompt you if you kill a query which is not sent by TablePlus.

**Comment by manseuk** [comment] 2019-06-06 07:34
OK thanks - i will update the safe mode and retry. Thanks for the update - its going to mean i can finally kill off MySQL Workbench

**Comment by ruudk** [comment] 2019-06-06 07:46
> TablePlus now can kill unresponsive query on MySQL
> Download: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
> Let me know if anyone encounters any problems.

Can you publish this to Github next time? I'm quite surprised people will just take a binary from Dropbox and install it on their machine to connect to their database 😱

**Comment by ruudk** [comment] 2019-06-06 07:46
Kudos for fixing this btw 👏

**Comment by alexGitSpace** [comment] 2020-12-23 15:56
> TablePlus now can kill unresponsive query on MySQL
> Download: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
> Let me know if anyone encounters any problems.

@huyphams, I have the same issue with cancelling unresponsive query on **Redshift** DB (version 1.0.22169).
Steps to reproduce:
1. Launch a long query (q1) in a window
2. In another window run a light query (q2). It looks like it doesn't start executing until the first request completes
3. I can only cancel (kill) the q1

I am using licensed TablePlus (Version 3.12.0 (354)).
Thanks in advance !

**Comment by mtami** [comment] 2021-06-01 16:11
**TablePlus Version:** 3.12.8 (369)
**Redshift cluster:** (PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.26742)

Hi @huyphams 
I encounter the same problem while connecting to Redshift cluster (PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.26742).

steps to reproduce reproduce:
1- run complex/long query
2- hit the cancel button (Command+. )
3- a PopUp UI for initializing the running query.
 
No query is shown into the popup ui, i have to wait until the query returned itself, or restart the app.
