### ISSUE TITLE
Only Intel version is available on SetApp, please, provide the M1 version there as well

### ISSUE THREAD

**Issue by cperezabo** [TablePlus/TablePlus#2617] opened 2022-03-03 21:47 UTC
Please, fix that, I don't understand why you are not providing the M1 version you already have compiled in SetApp

**Comment by huyphams** [comment] 2022-03-04 00:00
Duplicate of https://github.com/TablePlus/TablePlus/issues/2180

**Closed by huyphams** 2022-03-04 00:00 UTC

**Comment by cperezabo** [comment] 2022-03-04 23:23
Oh, so you are leaving SetApp, you have lost many users including me just like this! I've recommended TablePlus for a long time, but not anymore. You cannot abandon users just because you are too lazy in order to provide a Universal macOS Binary like the rest of developers do in SetApp which support both Intel and M1. The Oracle thing is not an excuse. Sorry
