### ISSUE TITLE
Allow query parameters in SQL query window

### ISSUE THREAD

**Issue by ndastur** [TablePlus/TablePlus#430] opened 2018-05-20 09:24 UTC
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9 and 10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
106

3. The steps to reproduce this issue:
New feature

Noted: If the bug is related to data, please attach an example SQL data.

It would be really great if SQL statements could be written with query parameter placeholders and then the parameters set in a key / value form. It would make scripts much safer as devs could then prototype SQL statements directly in TP as they will use in the applications.

**Comment by huyphams** [comment] 2018-05-21 03:52
Thanks for the suggestion, but I want to confirm the feature. Is this what you're looking for?
<img width="212" alt="screen shot 2018-05-21 at 10 51 00 am" src="https://user-images.githubusercontent.com/3654622/40289868-056de904-5ce5-11e8-808d-ae06115eb18e.png">

**Comment by ndastur** [comment] 2018-05-21 13:07
Hi @huyphams . No not really. I was think more about being able to use a SQL statement like:

```
select * from users where firstname ilike $1;
```

And then there would be a key / value form with two columns

```
| Parameter Position | Value        |
====================================
|  1                 | param_value  |
```

**Comment by fairchild** [comment] 2018-06-09 14:43
Similarly, 

```ruby
"select * from users where firstname ilike  #{name};"
```  

That would allow ruby devs to use it in most simple string interpolation cases I run into day to day.  This would be very handy.  I find myself going thru hoops with some weird spacing  and commented lines to dial in a query in TablePlus, and then pasting back into code, with extra work and occasional error.  It would be handy to be able to specify 

It would be super awesome if it were possible to select the string interpolation type, such as
```python
'select * from users where firstname ilike  {name};'
```   
for python and .net

**Comment by nutmix** [comment] 2019-06-17 08:38
Please can you add "prepared" statement type  parameters using this well established standard:

select * from foo where foo.bar like :baz;

or 

select * from foo where fool.stat between :start and :end

This is the standard used by Toad for oracle, and also by heidisql for mysql. It is used by a number of ORMs to store your sql in your code. Thus you can test your codes prepared statements, without editing (which is a significant source of errors).

The other advantage is if you have a large piece (e.g. with several sub queries which all share the same parameter), you only have to define and edit the parameter in one place, and can reused it.  The parameter editor should allow the standard formats (dates, timestamps, strings, decimals etc)

For our development team, without this feature we cannot use tableplus, we have to stick with heidisql on wine for mac, which is somewhat painful (e.g. you cant see buttons and fonts are rendered badly)

**Comment by ndastur** [comment] 2019-06-17 09:04
Some sort of parametrised feature would be really helpful. I agree with the editing of our source SQL is tedious and a source of errors. As for positional parameters ($1 ...) they are a standard SQL variant vs named parameters. I'd have thought the implementation shouldn't be too different.

**Comment by huyphams** [comment] 2019-06-17 09:09
We're going to implement this feature, here is the solution.

1. User can describe the params syntax (it should be a regex). and the default is :<number+alphabet>
so you guy can choose your favorite variable pattern.
2. TablePlus will have a table with two sections, global variable which will apply for all queries without asking and local variable which will ask every time user run a script.
 - User can manage the global variable section and save it as a template.
 - The local section will be reset after running a query.
3. TablePlus will detect all variable and show in the variable table, ignore quote, comments etc...

**Comment by huyphams** [comment] 2019-06-17 09:14
4. TablePlus will highlight all string which is matched the variable regex.
5. This feature is turned off by default and you must enable it, here is how to do it:
<img width="634" alt="Screen Shot 2019-06-17 at 4 11 18 PM" src="https://user-images.githubusercontent.com/3654622/59592601-9070ce80-911a-11e9-91c1-315c37652f38.png">

We will release it as soon as possible but in the beta channel first, and of course, we can't make it in the next official release (this week) because all the features are planned. So if you want to use it, please enable beta update (preferences) we will release it on the next beta.

**Comment by ndastur** [comment] 2019-06-17 09:16
Great news!

**Comment by tonyxiao** [comment] 2019-06-17 14:24
This is incredible, looking forward to trying it!!

**Comment by huyphams** [comment] 2019-06-18 02:57
Hey guys, now we can download the experiment here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
`Not all features are supported but at least, you can see how it works.`

![2019-06-18 09 54 30](https://user-images.githubusercontent.com/3654622/59650147-281ffc80-91af-11e9-826b-8d96468521d3.gif)

**Comment by chrschmitz** [comment] 2019-06-18 06:38
Do you have an idea, why it does not work on my system?

Error message:
Query 1 ERROR: ERROR:  syntax error at or near ":"
LINE 1: select :cols from "Rank" limit :n;

**Comment by huyphams** [comment] 2019-06-18 06:39
Hey @chrschmitz you must enable the query params, see my previous comments in this post.

**Comment by chrschmitz** [comment] 2019-06-18 06:58
Awesome! This is a game changer!

I found one issue:

If you write the command twice and run both queries...
```
select :cols from comments limit :n;
select :cols from comments limit :n;
```
... the first query does not resolve :n and the second query does not resolve :cols.

Is it possible to store the input values between runs? If you run the same query multiple times you have to enter the values over and over.

**Comment by huyphams** [comment] 2019-06-18 07:52
I've updated the dropbox link above to fix the parsing but @chrschmitz thank you!

**Comment by chrschmitz** [comment] 2019-06-18 09:03
You guys are amazing! I can confirm that the previously reported bug is fixed :-) I do not know a single group fixing bugs so blazingly fast.

Apart from the (obviously not yet implemented) option of global variables, it would be great if you would consider storing local variables at least during the current session.

With new features new wishes come up ;-) Have you considered to set local variables in the SQL script?

Example:
SET :cols = 'id, comment';
SET :id = '10';

**Comment by alvint** [comment] 2019-06-18 21:11
Hi, will global variables be highlighted differently from local variables? This might avoid unexpected mistakes.

**Comment by huyphams** [comment] 2019-06-19 03:12
@alvint I've changed the behavior and decided not to implement the global in this release.
- TablePlus now remember the old query parameters.
- TablePlus will highlight the parameters if it's active in the query (see the attached image).
- TablePlus will ask for parameters if the input contains any parameters.

The beta is released so I will close this issue for now.

<img width="1463" alt="parameters" src="https://user-images.githubusercontent.com/3654622/59734221-bf9e5180-927a-11e9-885f-63f17d20eb57.png">

**Closed by huyphams** 2019-06-19 03:12 UTC
Labels: enhancement, waiting-user-feedback

**Comment by junjizhi** [comment] 2019-09-20 18:28
@huyphams How do you pass parameters as strings with quotes? For postgres, I tried:

```
select * from table where col = :param;
```
but it didn't work when I set the value to `'target'` (with quotes)

then I tried: 

```
select * from table where col = ':param';
```
then it query runner didn't detect the parameter and executes.

Am I missing something here?

**Comment by huyphams** [comment] 2019-09-20 18:49
TablePlus will ignore all the params in the quote (and it should) because the string inside the quote can have `:`
You can write your query this way:
select * from table where col = :param;

And the params should be some string `include` quote 'somestring'

**Comment by junjizhi** [comment] 2019-09-21 00:11
Including quotes in the params value wont work because quotes gets stripped when it is actually executed. I tried that.

**Comment by huyphams** [comment] 2019-09-21 00:14
Please double-check @junjizhi it doesn't seem to be stripped, please see my attachment. I've tested the single quote as well.
<img width="660" alt="Screen Shot 2019-09-20 at 9 13 26 PM" src="https://user-images.githubusercontent.com/3654622/65364938-9aa7da80-dbeb-11e9-815a-631b824a2305.png">

**Comment by junjizhi** [comment] 2019-09-21 02:24
Nope. Didn't work for me.

<img width="750" alt="image" src="https://user-images.githubusercontent.com/2715151/65366685-3a1d9b00-dbf5-11e9-944a-307b76cd3704.png">

<img width="475" alt="image" src="https://user-images.githubusercontent.com/2715151/65366689-515c8880-dbf5-11e9-8c72-c3b98dc270c2.png">

**Comment by huyphams** [comment] 2019-09-21 02:31
Hey @junjizhi could you make a gif please with gifox.io
it's so weird, please check out this gif, this exactly the input but it works.
![2019-09-20 23 29 48](https://user-images.githubusercontent.com/3654622/65366779-b10b6180-dbfe-11e9-9472-59f60969522b.gif)

**Comment by junjizhi** [comment] 2019-09-21 02:35
Yeah. That's strange. I did exactly the same thing. 

My db is PostgreSQL 9.6.13. not sure if it's related.

TablePlus version is Version 2.9 (262)

**Comment by junjizhi** [comment] 2019-09-21 02:42
![2019-09-20 22 40 49](https://user-images.githubusercontent.com/2715151/65366872-e19bcd00-dbf7-11e9-9d30-c7d6d9dd90ab.gif)

**Comment by huyphams** [comment] 2019-09-21 02:45
Wow, do you use any keyboard input program? I seem that it was a UI issue, which ignores the last character.
Could you please try again and before pressing apply, please click outside to make sure that the value is entered correctly, like this gif.
![2019-09-20 23 45 00](https://user-images.githubusercontent.com/3654622/65366924-b9649c00-dc00-11e9-94f6-ca1c7f47d606.gif)

**Comment by junjizhi** [comment] 2019-09-21 02:51
Interesting. Clicking outside or hitting enter key before apply worked. 👍

**Comment by huyphams** [comment] 2019-09-21 02:54
I think it's related to the Apple input source method, which does not commit the last character (if you enable native input source, it will have an underscore)
<img width="99" alt="Screen Shot 2019-09-20 at 11 53 10 PM" src="https://user-images.githubusercontent.com/3654622/65367011-d188eb00-dc01-11e9-8b63-bc65e3d788cf.png">
and it's not actually entered, it will be stripped if you click apply.

**Comment by huyphams** [comment] 2019-09-21 03:12
Btw, I fixed that issue, now TablePlus will end editing before applying, it will work now and no need to click outside, thank you @junjizhi

**Comment by junjizhi** [comment] 2019-09-21 06:49
👍

**Comment by mrmurphy** [comment] 2019-10-07 19:23
Wonderful, @huyphams did you ever add the ability to customize the regex? We want to use the symbols that our driver uses, `?`. It appears to be hard-coded to recognize colons at the moment, but we're using colons to cast datatypes, like this: `'foo'::jsonb`.

**Comment by huyphams** [comment] 2019-10-07 19:36
Currently, it's hardcoded but I can change it easily, maybe we should allow the user to edit the regex in the variable popup.
<img width="247" alt="Screen Shot 2019-10-07 at 4 35 03 PM" src="https://user-images.githubusercontent.com/3654622/66342749-87517a80-e920-11e9-858c-26b51eb92cbf.png">

**Comment by mrmurphy** [comment] 2019-10-07 19:39
Sounds super!

**Comment by huyphams** [comment] 2019-10-07 20:54
Hi @mrmurphy please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
You can change the regex (from a list with a few options).
<img width="661" alt="Screen Shot 2019-10-07 at 5 53 58 PM" src="https://user-images.githubusercontent.com/3654622/66347762-73f7dc80-e92b-11e9-9000-536e2f9d791a.png">

**Comment by mrmurphy** [comment] 2019-10-07 21:00
wow, Henry, thanks for the fast turnaround! Seems I'm having trouble getting the question mark to work:

<img width="992" alt="image" src="https://user-images.githubusercontent.com/1227109/66348184-31c2a100-e913-11e9-9c9a-3b58fba7ad4b.png">

When I execute the query I'd expect to see a dialogue pop up asking for query params. Instead I see the runtime error and no dialogue pops up at all.

**Comment by huyphams** [comment] 2019-10-07 22:23
Thank you @mrmurphy please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
I've added some improvements

**Comment by mrmurphy** [comment] 2019-10-07 22:28
That worked very nicely, thank you!

**Comment by mrmurphy** [comment] 2019-10-08 03:17
Aaah you know what would be really helpful? If I could also get the Scala / Slick interpolation syntax added to the dropdown menu.

<img width="473" alt="image" src="https://user-images.githubusercontent.com/1227109/66364633-a8799180-e947-11e9-8810-4fec18eec7aa.png">

Their interpolation syntax (translates into prepared statements on the back-end) is a dollar-sign, followed by square braces, and some expression in-between the braces `${foo.bar.whatever}`. I'd love to be able to just paste that query into table plus and specify a value to substitute for the expression inside the braces at runtime.

**Comment by huyphams** [comment] 2019-10-08 16:08
I've added it on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
@mrmurphy

**Comment by mrmurphy** [comment] 2019-10-08 16:16
Awesome! I just tried it out, and it works really well if the only thing I have inside of the braces are word characters, but if I have dots or underscores in there, the pattern doesn't match anymore.

Any objection to changing the pattern to something like this?
`\$\{[^\}]+\}`

That pattern should match any characters which are not a closing brace until a closing brace is found, and allow for any expression inside of the braces.

**Comment by mrmurphy** [comment] 2019-10-08 21:30
You know, it might not be worth it, the "Beautify" command destroys that ${} formatting anyway, stripping out the curly braces, so I'm not sure I could use the interpolation regularly anyway.

**Comment by huyphams** [comment] 2019-10-16 16:27
I've fixed all the issue related to the variable with Beautify: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks @mrmurphy

**Comment by mrmurphy** [comment] 2019-10-16 16:38
Hmm, I just tried it out @huyphams but it looks like the regex pattern isn't properly pickup up somehow?
<img width="424" alt="image" src="https://user-images.githubusercontent.com/1227109/66939857-16d1ea00-f001-11e9-8317-88e17d8dca67.png">

**Comment by huyphams** [comment] 2019-10-16 16:40
Because the regex was \w+ it must not contains dot

**Comment by mrmurphy** [comment] 2019-10-16 16:41
Oh that's right. Sorry. Would it be possible to change the regex to something like this?
`\$\{[^\}]+\}` to allow for any non-curly brace characters inside the braces?

**Comment by mrmurphy** [comment] 2019-10-16 16:44
Ah, prettify works when there's no "dot" inside the braces, but not when there is a dot. This isn't a huge deal to me, though, just a nicety, so no pressure. I'm glad to let this go in favor of other features.

**Comment by huyphams** [comment] 2019-10-16 16:46
I've updated it to [\w.]+ now it should work for the case with dot too.

**Comment by mrmurphy** [comment] 2019-10-16 17:28
Okay, thanks!

**Comment by huyphams** [comment] 2019-10-16 17:40
it should work now: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks @mrmurphy

**Comment by AgustinBanchio** [comment] 2020-02-10 16:10
Query Params like $1, $2, $3... are not working, even though the regex `\$[\w.]+` should match.
It works fine with $variable but not with just digits.
 ERROR:  there is no parameter $3

**Comment by elmpp** [comment] 2021-01-19 11:20
How does one input multiple instances of the same parameter placeholder? I am using the `?` regex as shown here:

<img width="1167" alt="Screenshot 2021-01-19 at 12 19 12" src="https://user-images.githubusercontent.com/864612/105027849-8dedfd80-5a50-11eb-88d7-ca30d925e607.png">


But i can't seem to find how to input for both params:

<img width="1461" alt="Screenshot 2021-01-19 at 12 17 59" src="https://user-images.githubusercontent.com/864612/105027720-626b1300-5a50-11eb-9691-6baeff709a2a.png">

**Comment by huyphams** [comment] 2021-01-19 11:23
Hi @elmpp please use differrent variable regex

**Comment by elmpp** [comment] 2021-01-19 15:17
The regex is correct but as you can see in the images it has matched 2
times. How do i enter the values to be replaced?

i have tried `value1,value2` / `"value1","value2"`. etc etc

**Comment by huyphams** [comment] 2021-01-19 15:19
The question mark ? is only use for 1 variable. If you want to use it for multiple variables please change it to :w+  

For example: select * from :name1 as :name2

**Comment by elmpp** [comment] 2021-01-19 15:27
hmmm then it seems that this format of parameters is not supported then?

`select * from ? where name = ?`.  Parameters are then ['users', 'myName']

I don't understand why there is a regex option for `\?` if the UI does not
support multiple matches of a single placeholder

**Comment by iaj** [comment] 2022-07-01 08:10
Hey folks,
thanks for that great tool and all its greatness with query params... I've now also run into that issue, which I use alot, and would love to have ' ignored for queryparams -- because I would have several places, where I then would always have to use 'foo' with the quotes for substitution.

UPDATE vid_benutzer set loginallowed='N', status='N', ldate=NOW() where kennung = ${kuerzel};

Like here, is that also possible to achieve with some way like that?
UPDATE vid_benutzer set loginallowed='N', status='N', ldate=NOW() where kennung = '${kuerzel}';

Thanks!

**Comment by huyphams** [comment] 2022-09-26 04:37
Hi @iaj it will be possible in the next update if you enable this option:
<img width="610" alt="CleanShot 2022-09-26 at 11 37 17@2x" src="https://user-images.githubusercontent.com/3654622/192194840-d24a8c1f-f7b8-4bdc-845c-e8dbb7518b43.png">

**Comment by huyphams** [comment] 2022-10-04 15:41
Why would you need to clean up those variables as they do not get applied anyway?

**Comment by iaj** [comment] 2022-10-05 05:17
@huyphams yeh its odd… but I cant change the value for :schluessel - only when I clean up I am allowed to change the input field there

**Comment by huyphams** [comment] 2022-10-05 05:19
I don't see any variable with name :schluessel
Have you tried to double click to the value field?

**Comment by iaj** [comment] 2022-10-05 05:22
I ment :kuerzel sorry— yeah I tried it blinks up red and wont let me do changes

**Comment by huyphams** [comment] 2022-10-05 05:23
Could you make a screencast or a gif, please? I could not reproduce the issue/
Thank you in advance,

**Comment by iaj** [comment] 2022-10-06 07:06
Hi @huyphams,

sure, sorry, here it comes, I'm running TablePlus 5.0.0 (455)

Thanks in advance
![tableplus_query_parameter_not_changeable](https://user-images.githubusercontent.com/36959/194236486-ecccdc72-1f47-41bc-9712-905660a7e116.gif)

**Comment by huyphams** [comment] 2022-10-06 13:12
Hmm weird, let me check it.

**Comment by huyphams** [comment] 2022-10-06 13:42
If you have a chance, please try this patch and see how it goes: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
@iaj

**Comment by iaj** [comment] 2022-10-06 14:47
@huyphams I tried the patch -- but it still won't lemme change the param:

<img width="520" alt="CleanShot 2022-10-06 at 16 46 24@2x" src="https://user-images.githubusercontent.com/36959/194344545-e4e82e0d-5127-4d47-99d5-154b7466300a.png">

**Comment by huyphams** [comment] 2022-10-06 15:31
How about this patch https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Thanks @iaj

**Comment by iaj** [comment] 2022-10-06 15:34
@huyphams same :-(  it just  stays red and wont lemme allow to put anything inside of it :(

**Comment by huyphams** [comment] 2022-10-07 04:01
Weird, can I have your email @iaj you can say hello to our support team at nick@tableplus.com we will send you a hot patch/debug build to find out the issue.
