### ISSUE TITLE
DB backup progress indicator.

### ISSUE THREAD

**Issue by wayneforrest** [TablePlus/TablePlus#2121] opened 2020-10-05 09:14 UTC
1. MariaDB 10.5.5

2. 3.9.1 build (342)

3. Start a backup of a database.

It would be nice to have some indicator.. I know it is would be hard to have a progress bar but how about this:

1: Show the time the backup was started:
2: Show for how long the backup has been running in hours:minutes:seconds
3: How many lines have written to the file.

I noticed that DBeaver shows the amount of lines written to the file as the backup takes place.

**Comment by huyphams** [comment] 2020-10-05 09:40
Hi @wayneforrest if you backup the database using export (just like DBeaver) TablePlus will show you the indicator.

<img width="499" alt="Screen Shot 2020-10-05 at 4 40 25 PM" src="https://user-images.githubusercontent.com/3654622/95064132-7c931680-0729-11eb-8fc0-ee6f06f30add.png">

It's not possible to show indicator with the native binary (which is used for backup/restore feature) as it isn't implemented by the PostgreSQL/MySQL, also it's a duplicate of
 https://github.com/TablePlus/TablePlus/issues/945

**Closed by huyphams** 2020-10-05 09:40 UTC

**Comment by wayneforrest** [comment] 2020-10-05 09:45
DBeaver using mysqldump behind the scenes and has a line count as I backup.

**Comment by gjuchault** [comment] 2020-11-18 09:48
> It's not possible to show indicator with the native binary
I think it is 🤔 
https://stackoverflow.com/a/4853519

**Comment by mijewe** [comment] 2021-02-25 12:41
If this is possible, could this be reopened?

I've got some chunky database imports and not knowing whether it's crashed or not is frustrating.
