### ISSUE TITLE
Multiple windows are merged

### ISSUE THREAD

**Issue by aramando** [TablePlus/TablePlus#1291] opened 2019-07-08 13:28 UTC
I've noticed that when I have 2 workspaces open in 2 windows, after a while one of the windows will disappear and I will have gained a "tab bar" with tabs for the workspaces. This is the same behaviour as can be activated using the menu option Window -> Merge all windows.

Apart from being confusing, this is a problem because of #1290  - when the app uses the "tab" bar to represent workspaces, it obscures the real tabs, i.e. the different table or query views open in each workspace.

1. Which driver are you using and version of it: PostgreSQL 10.6
2. Which TablePlus build number are you using: 244
3. The steps to reproduce this issue:
   - Open two windows with 2 different workspaces using Cmd+N
   - Wait a while
   - Multiple windows are eventually merged into one with tabs for the workspaces

**Comment by aik099** [comment] 2019-07-10 16:09
I can confirm, that tab bar (from window merging) is overlapping top row in each of the windows.

**Comment by ruudk** [comment] 2019-08-22 11:20
I have exactly the same. This is how it looks like:
<img width="2548" alt="Image 2019-08-22 at 1 18 41 PM" src="https://user-images.githubusercontent.com/104180/63510730-a2d30400-c4df-11e9-9de2-1e87be8bb058.png">

**Comment by huyphams** [comment] 2019-08-22 11:51
Hey @ruudk it was fixed on the prerelease build, you can try it here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
(this build can self-update when the official is released)

**Closed** 2020-05-08 10:00 UTC
Labels: bug, fixed
